BackofficeBundle/Controller/AbstractAdminController.php
BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Form/Type/ContentTypeType.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/Form/Type/ContentTypeTypeTest.php

Belongs to a pool of 3 PR :
open-orchestra-cms-bundle, open-orchestra-model-bundle, open-orchestra-model-interface

Add edit form custom template for content

---

BackofficeBundle/EventSubscriber/FieldTypeTypeSubscriber.php
BackofficeBundle/Tests/EventSubscriber/FieldTypeTypeSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/50
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/280

check content attribute option

---

BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/EventSubscriber/ContentTypeSubscriber.php
BackofficeBundle/Tests/EventSubscriber/ContentTypeSubscriberTest.php

3 PR concomitantes :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/702
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/283
https://github.com/open-orchestra/open-orchestra-model-interface/pull/53

Fix content edit

---

BackofficeBundle/Resources/views/BackOffice/Underscore/Include/superboxView_crop._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/Include/superboxView_meta._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/superboxView._tpl.twig

https://trello.com/c/YAQFAdN4/839-1-etq-ubo-je-vois-l-onglet-crop-uniquement-pour-les-images

remove crop tab on non image media

---

BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Form/Type/FieldTypeType.php
BackofficeBundle/Resources/config/fieldtype.yml
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

+ add translation
https://trello.com/c/1Yn20BSP/846-2-etq-ubo-je-peux-ajouter-des-contents-attributs-specifique

Allow user to add content type attributes

---

MediaAdminBundle/Resources/config/display.yml
MediaAdminBundle/Resources/config/icon.yml
MediaAdminBundle/Resources/config/leftpanel.yml

revert wrong tags

---

MediaAdminBundle/EventSubscriber/MediaCacheInvalidateSubscriber.php
MediaAdminBundle/Resources/config/subscriber.yml
MediaAdminBundle/Tests/EventSubscriber/MediaCacheInvalidateSubscriberTest.php

should fix https://github.com/open-orchestra/open-orchestra-cms-bundle/issues/703 @juchi

rename chache to cache

---

MediaAdminBundle/Resources/views/Form/form_div_layout.html.twig

put back custom form types

---

ApiBundle/Controller/ContentController.php
BackofficeBundle/Resources/config/display.yml

In relation with: 
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/297
https://github.com/open-orchestra/open-orchestra-model-interface/pull/64

Add language into paramater method repository

---

Backoffice/LeftPanel/Strategies/GeneralNodesPanelStrategy.php
BackofficeBundle/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/66

change const name

---

BackofficeBundle/Resources/views/Tree/tree-macros.html.twig

@itkg-ngilain I have found the origin of the issue

fix node translation

---

Backoffice/LeftPanel/Strategies/ContentTypeForContentPanelStrategy.php
BackofficeBundle/Resources/config/leftpanel.yml

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/322
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/807

Sort Content Types by name in the BO locale

---

UserAdminBundle/Tests/Functional/Repository/UserRepositoryTest.php

in relation with https://github.com/open-orchestra/open-orchestra-user-bundle/pull/58

add test functional for user repository

---

ApiBundle/Controller/NodeController.php

in relation with https://github.com/open-orchestra/open-orchestra-model-bundle/pull/327

update cursorIterator is change in ArrayIterator

---

GruntTasks/Options/symlink.js

https://github.com/open-orchestra/open-orchestra/issues/459

fix duplicate entry in grunt symlink task

---

BackofficeBundle/EventSubscriber/AbstractModulableTypeSubscriber.php

use the transformer in the right way for the reverse transform

---

BackofficeBundle/Form/Type/FieldTypeType.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/Form/Type/FieldTypeTypeTest.php

add immutable fields and properties of content

---

BackofficeBundle/Resources/public/coffee/table/TableviewCollectionView.coffee

fix this issue https://github.com/open-orchestra/open-orchestra-cms-bundle/issues/837

fix link back_to_list in fullpageFormView

---

LogBundle/DependencyInjection/OpenOrchestraLogExtension.php

https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/18
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/844
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/55
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/333
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/9

Replace deprecated method definition->setFactory*

---

BackofficeBundle/Resources/config/group.yml

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/60
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/846
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/19

Replace factory service in yaml

---

MediaAdminBundle/Form/Type/FolderType.php
MediaAdminBundle/Tests/Form/Type/FolderTypeTest.php
MediaAdminBundle/Tests/Functional/Controller/FolderControllerTest.php

fix folder save

---

BackofficeBundle/Resources/config/initializer.yml
BackofficeBundle/Resources/views/BackOffice/Include/Header/languageDropdown.html.twig
UserAdminBundle/Resources/config/form.yml

https://github.com/open-orchestra/open-orchestra-base-bundle/pull/27
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/859

Rename param container administration_languages

---

MediaAdminBundle/Resources/public/coffee/bindExtendView.coffee

fix this issue https://github.com/open-orchestra/open-orchestra/issues/517

fix bug mediaModal form content

---

ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
Backoffice/Context/TestContextManager.php

https://github.com/open-orchestra/open-orchestra/pull/534
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/22
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/30
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/890
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/344
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/99
https://github.com/open-orchestra/open-orchestra-front-demo/pull/42

Fix preview

---

MediaAdminBundle/Tests/Functional/Controller/MediaControllerTest.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/65
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/925

Update media functionnal tests

---

BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
MediaAdminBundle/DisplayBlock/Strategies/CarrouselStrategy.php
MediaAdminBundle/DisplayIcon/Strategies/CarrouselStrategy.php
MediaAdminBundle/GenerateForm/Strategies/CarrouselStrategy.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/930
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/68

Remove Carrousel strategy dependancy

---

MediaAdminBundle/Resources/public/coffee/WysiwygSelectView.coffee

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/932
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/157
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/368

Fix media url problem in tinymce

---

ApiBundle/Facade/FieldTypeFacade.php
BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/EventSubscriber/ContentTypeSubscriber.php
BackofficeBundle/EventSubscriber/FieldTypeTypeSubscriber.php
BackofficeBundle/Form/DataTransformer/ChoiceArrayToStringTransformer.php
BackofficeBundle/Form/DataTransformer/ChoiceStringToArrayTransformer.php
BackofficeBundle/Form/Type/FieldTypeType.php
BackofficeBundle/Form/Type/OrchestraFieldChoice.php
BackofficeBundle/Resources/config/fieldtype.yml
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/transformer.yml
BackofficeBundle/Resources/public/coffee/extendView/contentTypeChange.coffee
BackofficeBundle/Resources/public/coffee/page/FieldOptionDefaultValueView.coffee
BackofficeBundle/Resources/public/coffee/viewConfigurator.coffee
BackofficeBundle/Tests/EventSubscriber/FieldTypeTypeSubscriberTest.php
BackofficeBundle/Tests/Form/DataTransformer/ChoiceArrayToStringTransformerTest.php
BackofficeBundle/Tests/Form/DataTransformer/ChoiceStringToArrayTransformerTest.php
BackofficeBundle/Tests/Form/Type/FieldTypeTypeTest.php
BackofficeBundle/Tests/Form/Type/OrchestraFieldChoiceTest.php
GruntTasks/Options/concat.orchestrajs.js

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/953
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/382

add dynamic default value field

---

ApiBundle/Controller/ApiClientController.php
ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Controller/GroupController.php
ApiBundle/Controller/KeywordController.php
ApiBundle/Controller/RedirectionController.php
ApiBundle/Controller/RoleController.php
ApiBundle/Controller/SiteController.php
ApiBundle/Controller/StatusController.php
BackofficeBundle/Resources/config/services.yml
GroupBundle/Tests/Functional/Repository/GroupRepositoryTest.php
LogBundle/Controller/LogController.php
LogBundle/Document/Log.php
UserAdminBundle/Controller/Api/UserController.php
UserAdminBundle/Tests/Functional/Repository/UserRepositoryTest.php

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/70
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/33
https://github.com/open-orchestra/open-orchestra-libs/pull/8
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1000
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/400
https://github.com/open-orchestra/open-orchestra-model-interface/pull/103
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/4

add annotation search

---

BackofficeBundle/Resources/public/coffee/FullPagePanelView.coffee

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/13
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1003

use extend view in panel view

---

Backoffice/NavigationPanel/Strategies/ContentTypeForContentPanelStrategy.php
Backoffice/NavigationPanel/Strategies/GSTreeTemplatePanelStrategy.php
Backoffice/NavigationPanel/Strategies/GeneralNodesPanelStrategy.php
Backoffice/NavigationPanel/Strategies/TreeNodesPanelStrategy.php
Backoffice/NavigationPanel/Strategies/TreeTemplatePanelStrategy.php
BackofficeBundle/Resources/config/navigation_panel.yml
LogBundle/Resources/config/navigation_panel.yml
UserAdminBundle/Resources/config/navigation_panel.yml

https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/37
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/17
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1009

add weight in navigation strategy

---

BackofficeBundle/Resources/public/coffee/tab/tabViewFormLoader.coffee

add use configuratorView for element tab

---

ApiBundle/Facade/ApiClientFacade.php
ApiBundle/Transformer/ApiClientTransformer.php
BackofficeBundle/Form/Type/ApiClientType.php
BackofficeBundle/Tests/Form/Type/ApiClientTypeTest.php

add role to client

---

ApiBundle/Controller/ApiClientController.php
ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Controller/GroupController.php
ApiBundle/Controller/KeywordController.php
ApiBundle/Controller/RedirectionController.php
ApiBundle/Controller/RoleController.php
ApiBundle/Controller/SiteController.php
ApiBundle/Controller/StatusController.php
BackofficeBundle/Resources/config/group.yml
LogBundle/Controller/LogController.php
LogBundle/DependencyInjection/OpenOrchestraLogExtension.php
UserAdminBundle/Controller/Api/UserController.php

https://github.com/open-orchestra/open-orchestra-libs/pull/11
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/71
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/39
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1019
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/6
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/406
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/49

Add strategy filter

---

ApiBundle/Controller/NodeController.php
BackofficeBundle/EventSubscriber/AbstractDeleteSubscriber.php
BackofficeBundle/EventSubscriber/DeleteContentSubscriber.php
BackofficeBundle/EventSubscriber/DeleteNodeSubscriber.php
BackofficeBundle/Manager/NodeManager.php
BackofficeBundle/Resources/config/subscriber.yml
BackofficeBundle/Tests/EventSubscriber/DeleteContentSubscriberTest.php
BackofficeBundle/Tests/EventSubscriber/DeleteNodeSubscriberTest.php
BackofficeBundle/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/109
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/413
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1033

refacto trash can

---

ApiBundle/Controller/ApiClientController.php
ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Controller/GroupController.php
ApiBundle/Controller/KeywordController.php
ApiBundle/Controller/RedirectionController.php
ApiBundle/Controller/RoleController.php
ApiBundle/Controller/SiteController.php
ApiBundle/Controller/StatusController.php
ApiBundle/Controller/TrashcanController.php
LogBundle/Controller/LogController.php
UserAdminBundle/Controller/Api/UserController.php

https://github.com/open-orchestra/open-orchestra/pull/637
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1039
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/46
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/43
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/421
https://github.com/open-orchestra/open-orchestra-libs/pull/19

move annotation reader to libs

---

BackofficeBundle/Resources/public/coffee/tinyMCE/html2bbcodeConfigurator.coffee

https://github.com/open-orchestra/open-orchestra-front-demo/pull/101
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1042
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/170

Remove wrong tags

---

BackofficeBundle/Form/DataTransformer/BBcodeToHtmlTransformer.php
BackofficeBundle/Form/Type/TinymceType.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/transformer.yml
BackofficeBundle/Tests/Form/DataTransformer/BBcodeToHtmlTransformerTest.php
BackofficeBundle/Tests/Form/Type/TinymceTypeTest.php

https://github.com/open-orchestra/open-orchestra-display-bundle/pull/172
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/107
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1051
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/29

Add a transformer to TinymceType to allow bbcode injection

---

ApiBundle/Controller/TranslationController.php
ApiBundle/Facade/TranslationFacade.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Transformer/TranslationTransformer.php
BackofficeBundle/Resources/public/coffee/tinyMCE/activateTinyMCE.coffee
BackofficeBundle/Resources/views/BackOffice/Include/contextualInformations.html.twig
BackofficeBundle/Resources/views/layout.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1073
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/38

Add translation Api and use it in TinyMce for custom buttons

---

BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/39
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1074

fix a bug in form_div_layout.html.twig where labal_attr were never add to rendered form

---

BackofficeBundle/DataFixtures/MongoDB/AbstractLoadRoleData.php
BackofficeBundle/DataFixtures/MongoDB/LoadRoleData.php
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewAction.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Include/MainPanel/ribbon.html.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/tableviewActions._tpl.twig
UserAdminBundle/DataFixtures/MongoDB/LoadRoleData.php

https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/57
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/43
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/436
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1083

Add translation to several strings

---

BackofficeBundle/Manager/RouteDocumentManager.php
BackofficeBundle/Tests/Manager/RouteDocumentManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1124

1.0 prevent route creation

---

BackofficeBundle/Manager/RouteDocumentManager.php
BackofficeBundle/Tests/Manager/RouteDocumentManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1123

prevent route creation if no published node exists

---

BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

Split orchestra and smartadmin

---

GroupBundle/DataFixtures/MongoDB/LoadGroupData.php
GroupBundle/Tests/Functional/Repository/GroupRepositoryTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1163
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/131
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/62

1.1 add roles on media folders

---

BackofficeBundle/Controller/AbstractAdminController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/BackofficeBundle/Controller/BlockController.php#L41
The option can be set upstream

fixed editing of node when is status published

---

BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Form/Type/OrchestraRoleChoiceType.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Tests/Form/Type/OrchestraRoleTypeTest.php

add workflow role in group

---

UserAdminBundle/DependencyInjection/OpenOrchestraUserAdminExtension.php
UserAdminBundle/EventSubscriber/DeleteGroupSubscriber.php
UserAdminBundle/Resources/config/subscriber.yml
UserAdminBundle/Tests/EventSubscriber/DeleteGroupSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/78

Remove group ref in user

---

BackofficeBundle/Form/Type/GroupType.php
BackofficeBundle/Form/Type/RoleType.php
BackofficeBundle/Form/Type/SiteType.php
UserAdminBundle/Controller/Admin/UserController.php
UserAdminBundle/Form/Type/RegistrationUserType.php
UserAdminBundle/Form/Type/UserType.php
UserAdminBundle/Resources/config/form.yml
UserAdminBundle/Tests/Form/Type/RegistrationUserTypeTest.php
UserAdminBundle/Tests/Form/Type/UserTypeTest.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/129
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/465
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/77
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/68

Rename form name

---

BackofficeBundle/Form/Type/AbstractGroupChoiceType.php
BackofficeBundle/Form/Type/GroupType.php
BackofficeBundle/Form/Type/RoleType.php
BackofficeBundle/Form/Type/SiteType.php
GroupBundle/Form/Type/GroupDocumentType.php
GroupBundle/Resources/config/services.yml
GroupBundle/Tests/Form/Type/GroupDocumentTypeTest.php
UserAdminBundle/Form/Type/UserType.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/130
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/466
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/70

rename oo_orchestra forms

---

ApiBundle/Controller/ThemeController.php
ApiBundle/Facade/ThemeCollectionFacade.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/469
https://github.com/open-orchestra/open-orchestra-model-interface/pull/133
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1213

fix count of themes in datatable view

---

UserAdminBundle/EventSubscriber/DeleteGroupSubscriber.php
UserAdminBundle/OAuth2/Strategy/ResourceOwnerPasswordGrantStrategy.php
UserAdminBundle/Tests/EventSubscriber/DeleteGroupSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/82

add UserRepositoryInterface usage

---

ApiBundle/Controller/ContentController.php
ApiBundle/Controller/NodeController.php
BackofficeBundle/Resources/views/BackOffice/Underscore/dashboard/widget/draftContentsView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/dashboard/widget/draftNodesView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/dashboard/widget/lastContentsView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/dashboard/widget/lastNodesView._tpl.twig

Depends on https://github.com/open-orchestra/open-orchestra-model-bundle/pull/468.

Display only current site elements in dashboard.

---

ApiBundle/Controller/ControllerTrait/HandleRequestDataTable.php
ApiBundle/Controller/SiteController.php
BackofficeBundle/Repository/GroupRepositoryInterface.php
BackofficeBundle/Tests/Functional/Controller/EditNodeControllerTest.php
GroupBundle/Repository/GroupRepository.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/467
https://github.com/open-orchestra/open-orchestra-model-interface/pull/131
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/6
https://github.com/open-orchestra/open-orchestra-libs/pull/33
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1226
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/62
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/84

use pagination repository instead of documentRepository

---

BackofficeBundle/Resources/views/BackOffice/Underscore/deleteButton._tpl.twig

https://github.com/open-orchestra/open-orchestra-base-bundle/pull/56

add_delete_button_translation

---

BackofficeBundle/Resources/views/BackOffice/Underscore/orchestraModalView._tpl.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1231
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/88

revamp modal close button

---

BackofficeBundle/EventSubscriber/UpdateNodeRedirectionSubscriber.php
BackofficeBundle/EventSubscriber/UpdateRouteDocumentSubscriber.php
BackofficeBundle/Manager/RedirectionManager.php
BackofficeBundle/Manager/RouteDocumentManager.php
BackofficeBundle/Resources/config/services.yml
BackofficeBundle/Tests/EventSubscriber/UpdateNodeRedirectionSubscriberTest.php
BackofficeBundle/Tests/EventSubscriber/UpdateRouteDocumentSubscriberTest.php
BackofficeBundle/Tests/Functional/Controller/NodeControllerTest.php
BackofficeBundle/Tests/Manager/RedirectionManagerTest.php
BackofficeBundle/Tests/Manager/RouteDocumentManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1282
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/485
https://github.com/open-orchestra/open-orchestra-model-interface/pull/140
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/65

Clean redirection

---

BackofficeBundle/Resources/translations/role.en.yml
BackofficeBundle/Resources/translations/role.fr.yml
UserAdminBundle/Resources/translations/role.en.yml
UserAdminBundle/Resources/translations/role.fr.yml

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/106
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/76

rename role access

---

BackofficeBundle/Tests/Functional/Controller/NodeControllerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1328
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/502

fix test for multirun

---

ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Transformer/GroupTransformerTest.php
ApiBundle/Tests/Transformer/NodeGroupRoleTransformerTest.php
ApiBundle/Transformer/GroupTransformer.php
ApiBundle/Transformer/NodeGroupRoleTransformer.php
ApiBundle/Transformer/TransformerWithGroupContextInterface.php
ApiBundle/Transformer/TransformerWithGroupInterface.php
BackofficeBundle/Model/NodeGroupRoleInterface.php
GroupBundle/DataFixtures/MongoDB/LoadGroupData.php
GroupBundle/Document/NodeGroupRole.php
GroupBundle/EventListener/AbstractNodeGroupRoleListener.php
GroupBundle/EventListener/AddNodeGroupRoleForGroupListener.php
GroupBundle/EventListener/AddNodeGroupRoleForNodeListener.php
GroupBundle/EventListener/UpdateNodeGroupRoleListener.php
GroupBundle/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriber.php
GroupBundle/Exception/NodeGroupRoleNotFoundException.php
GroupBundle/Resources/config/services.yml
GroupBundle/Tests/EventListener/AbstractNodeGroupRoleListenerTest.php
GroupBundle/Tests/EventListener/AddNodeGroupRoleForGroupListenerTest.php
GroupBundle/Tests/EventListener/AddNodeGroupRoleForNodeListenerTest.php
GroupBundle/Tests/EventListener/UpdateNodeGroupRoleListenerTest.php
GroupBundle/Tests/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/71

Update inherit node group role

---

GruntTasks/Options/concat.libcss.js
GruntTasks/Options/concat.libjs.js
GruntTasks/Options/concat.smartadmincss.js
GruntTasks/Options/concat.smartadminjs.js
GruntTasks/Options/symlink.js
composer.json

https://github.com/open-orchestra/open-orchestra/pull/781
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1339
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/115
https://github.com/open-orchestra/open-orchestra-docs/pull/142

use composer extra assets

---

BackofficeBundle/Manager/NodeManager.php
BackofficeBundle/Resources/config/validation/node.yml
BackofficeBundle/Resources/config/validator.yml
BackofficeBundle/Resources/translations/validators.de.yml
BackofficeBundle/Resources/translations/validators.en.yml
BackofficeBundle/Resources/translations/validators.fr.yml
BackofficeBundle/Tests/Manager/NodeManagerTest.php
BackofficeBundle/Tests/Validator/Constraints/UniqueNodeOrderTest.php
BackofficeBundle/Tests/Validator/Constraints/UniqueNodeOrderValidatorTest.php
BackofficeBundle/Validator/Constraints/UniqueNodeOrder.php
BackofficeBundle/Validator/Constraints/UniqueNodeOrderValidator.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/144
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/503

Fix order on new node

---

BackofficeBundle/EventSubscriber/AddTransverseBlockSubscriber.php
BackofficeBundle/Tests/EventSubscriber/AddTransverseBlockSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1353
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/507
https://github.com/open-orchestra/open-orchestra-model-interface/pull/148

Update only required transverse node

---

ApiBundle/Facade/NodeFacade.php
ApiBundle/Transformer/NodeTransformer.php
BackofficeBundle/EventSubscriber/BoDirectionChildrenSubscriber.php
BackofficeBundle/EventSubscriber/TemplateChoiceSubscriber.php
BackofficeBundle/Form/Type/NodeType.php
BackofficeBundle/Manager/NodeManager.php
BackofficeBundle/Resources/public/coffee/extendView/addArea.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/EventSubscriber/BoDirectionChildrenSubscriberTest.php
BackofficeBundle/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/505
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1345
https://github.com/open-orchestra/open-orchestra-model-interface/pull/146

add bo direction in node

---

BackofficeBundle/Resources/views/layout.html.twig
GruntTasks/Options/concat.libcss.js
GruntTasks/Options/concat.smartadminpatchescss.js

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1350
https://github.com/open-orchestra/open-orchestra/pull/791

Change grunt tasks to restore IE9 compatibility

---

GruntTasks/Options/symlink.js
composer.json

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1358
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/120

Move js dependencies from Cms to MediaAdmin

---

BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1368
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/122

add option to add form legend in template

---

ApiBundle/Controller/KeywordController.php
ApiBundle/Facade/ThemeCollectionFacade.php
Backoffice/AuthorizeEdition/NodeVersionStrategy.php
Backoffice/GenerateForm/Strategies/AudienceAnalysisStrategy.php
Backoffice/Tests/Generator/files/generated/displayIcon/TestStrategy.php
Backoffice/Tests/Generator/files/generated/generateForm/TestStrategy.php
Backoffice/Tests/Generator/files/reference/displayIcon/TestStrategy.php
Backoffice/Tests/Generator/files/reference/generateForm/TestStrategy.php
Backoffice/Tests/Generator/files/skeleton/displayIcon/Strategy.php.twig
Backoffice/Tests/Generator/files/skeleton/generateForm/Strategy.php.twig
BackofficeBundle/Controller/SiteController.php
BackofficeBundle/DependencyInjection/Compiler/AbstractRoleCompilerPass.php
BackofficeBundle/EventSubscriber/UpdateChildNodePathSubscriber.php
BackofficeBundle/Form/Type/Component/ThemeChoiceType.php
BackofficeBundle/Resources/views/BackOffice/Include/contextualInformations.html.twig
GroupBundle/DataFixtures/MongoDB/LoadGroupData.php
GroupBundle/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriber.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1342
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/117
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/156

add new name to alternative file

---

BackofficeBundle/Resources/public/coffee/dashboard/widget/abstract/AbstractWidgetListView.coffee

[OO-BUGFIX] Truncate long label in dashboard widget

Truncate dashboard labels

---

BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/EventSubscriber/FieldTypeTypeSubscriber.php
BackofficeBundle/Form/Type/FieldTypeType.php
BackofficeBundle/Resources/config/field_type.yml
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/parameters.yml
BackofficeBundle/Tests/EventSubscriber/FieldTypeTypeSubscriberTest.php
BackofficeBundle/Tests/Form/Type/FieldTypeTypeTest.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/129
[OO-FEATURE] auto-select type of search in datatable for content field type

remove searchable type from field type and inject in subscriber

---

ApiBundle/Transformer/NodeTransformer.php

[OO-FEATURE] allow publushed node delete

delete published node

---

GroupBundle/DependencyInjection/Compiler/EntityResolverCompilerPass.php

https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/15
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1383
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/157
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/515
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/85
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/88

fixes #1373 supress deprecated

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/extendView/deleteTree.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee
BackofficeBundle/Resources/public/coffee/page/NodeFormView.coffee
BackofficeBundle/Resources/public/coffee/page/TemplateFormView.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewRestoreAction.coffee

[OO-BCBREAK] change way to load dataparameter in refresh menu context
[OO-BUGFIX] disable load dataparemeter in modal context

replace dsiplay menu by refresh menu

---

BackofficeBundle/Resources/public/coffee/underscoreTemplateLoader.coffee

[OO-BUGFIX] Fix infinite ajax call

use fix on infinite ajax call 1.1 for 1.0

---

GruntTasks/Targets/concat.lib_css.js

[OO-BUGFIX] Fix error 404 Jcrop.gif when a picture is cropped
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/134
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1391

add jcrop css in concat lib

---

BackofficeBundle/Resources/public/coffee/addPrototype.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

[OO-BUGFIX] Activate tinyMce in collection prototype context
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/135

add activate form in case of collection prototype

---

GruntTasks/Targets/concat.lib_css.js
GruntTasks/Targets/concat.smartadmin_patches_css.js
GruntTasks/Targets/symlink.js

[OO-BUGFIX] Fix error 404 Jcrop.gif when a picture is cropped

fix 404 jcrop gif env prod

---

BackofficeBundle/Resources/public/coffee/tab/tabViewFormLoader.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewAction.coffee
BackofficeBundle/Resources/public/coffee/table/tableviewLoader.coffee

[OO-BUGFIX] Suppress multiple load in panel context

fix multiple loads in panel context

---

Backoffice/Security/Authorization/Voter/StatusableVoter.php
Backoffice/Tests/Security/Authorization/Voter/StatusableVoterTest.php

[OO-FEATURE] Allow published node deletion

rm delete node right from statusableVoter

---

BackofficeBundle/Form/Type/Component/DatePickerType.php

[OO-BUGFIX] Datepicker in content forms

fix DatePickerType

---

Backoffice/EventListener/TranslateValueInitializerListener.php
Backoffice/Tests/EventListener/TranslateValueInitializerListenerTest.php
BackofficeBundle/Form/Type/ContentTypeType.php
BackofficeBundle/Form/Type/FieldTypeType.php
BackofficeBundle/Form/Type/GroupType.php
BackofficeBundle/Form/Type/RoleType.php
BackofficeBundle/Form/Type/StatusType.php
BackofficeBundle/Resources/config/services.yml
BackofficeBundle/Tests/Form/Type/ContentTypeTypeTest.php
BackofficeBundle/Tests/Form/Type/FieldTypeTypeTest.php
BackofficeBundle/Tests/Form/Type/GroupTypeTest.php
BackofficeBundle/Tests/Form/Type/RoleTypeTest.php
BackofficeBundle/Tests/Form/Type/StatusTypeTest.php

[OO-BCBREAK] Move BackofficeBundle listener

move listener

---

ApiBundle/Controller/AreaFlexController.php
ApiBundle/Transformer/AreaFlexTransformer.php
ApiBundle/Transformer/TransformerWithTemplateFlexContextInterface.php
BackofficeBundle/Resources/public/coffee/areaFlex/AreaFlexToolbarView.coffee
BackofficeBundle/Resources/public/coffee/areaFlex/AreaFlexView.coffee
BackofficeBundle/Resources/public/coffee/page/AreaView.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Underscore/areaFlex/areaFlexToolbarView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/areaFlex/areaFlexView._tpl.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1418
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/522
https://github.com/open-orchestra/open-orchestra-model-interface/pull/162

Action remove area

---

BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

[OO-FEATURE] add notification colors

fixes #1401 on notification type

---

ApiBundle/Controller/AreaFlexController.php
ApiBundle/Controller/TemplateFlexController.php
ApiBundle/Facade/AreaFlexFacade.php
ApiBundle/Tests/Transformer/AreaFlexTransformerTest.php
ApiBundle/Transformer/AreaFlexTransformer.php
ApiBundle/Transformer/TemplateFlexTransformer.php
Backoffice/EventSubscriber/AreaFlexRowSubscriber.php
BackofficeBundle/Resources/public/coffee/areaFlex/AreaFlexChannel.coffee
BackofficeBundle/Resources/public/coffee/areaFlex/AreaFlexToolbarView.coffee
BackofficeBundle/Resources/public/coffee/areaFlex/AreaFlexView.coffee
BackofficeBundle/Resources/public/coffee/templateFlex/TemplateFlexView.coffee
BackofficeBundle/Resources/public/less/templateFlex/areaFlex.less
BackofficeBundle/Resources/public/less/templateFlex/templateFlex.less
BackofficeBundle/Resources/views/BackOffice/Underscore/areaFlex/areaFlexToolbarView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/areaFlex/areaFlexView._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/templateFlex/templateFlexView._tpl.twig

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/525
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1435

Move area row

---

BackofficeBundle/Resources/views/BackOffice/Underscore/table/tableviewActions._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/table/tableviewRestoreAction._tpl.twig

[OO-FEATURE] Datatable action buttons are disabled if the user hasn't the rights

disable datatable buttons when no access

---

BackofficeBundle/Resources/config/field_type.yml

[OO-FEATURE] Remove max length option on email field type

[OO-FEATURE] Remove max length option on email field type

---

GruntTasks/Options/concat.libjs.js

[OO-BUGFIX] 1 0 remove lodash
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1441
https://github.com/open-orchestra/open-orchestra/pull/835

[OO-BUGFIX] 1 0 remove lodash

---

Backoffice/Security/Authorization/Voter/StatusableVoter.php
Backoffice/Tests/Security/Authorization/Voter/StatusableVoterTest.php

[OO-BUGFIX] Published nodes can be moved

Allow move published node

---

ApiBundle/Controller/NodeController.php
Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

[OO-MISC] Deleted nodes order is -1
https://github.com/open-orchestra/open-orchestra-model-interface/pull/164

Change node order on delete

---

Backoffice/Tests/Validator/Constraints/CheckVariableRoutePatternInMenuTest.php
Backoffice/Tests/Validator/Constraints/CheckVariableRoutePatternInMenuValidatorTest.php
Backoffice/Validator/Constraints/CheckVariableRoutePatternInMenu.php
Backoffice/Validator/Constraints/CheckVariableRoutePatternInMenuValidator.php
BackofficeBundle/Resources/config/validation/node.yml
BackofficeBundle/Resources/config/validator.yml
BackofficeBundle/Resources/translations/validators.en.yml
BackofficeBundle/Resources/translations/validators.fr.yml

[OO-BUGFIX] Nodes with dynamic route pattern can't be added in menus

Add validator on variable node routePattern in menu

---

BackofficeBundle/Resources/config/form.yml

[OO-BUGFIX] Remove native media option in tinymce context menu

Remove 'media' from tinymce context menu

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

[OO-BUFIX] Fix custom field selection on content type creation

Fix custom field selection on content type creation

---

ApiBundle/Controller/BlockController.php
ApiBundle/Transformer/NodeTransformer.php

[OO-BUGFIX] Don't display the transverse blocks in the blocks panel when editing a transverse node

Filter transverse blocks on transverse page

---

BackofficeBundle/Resources/public/coffee/addPrototype.coffee

fix prototype

---

BackofficeBundle/Resources/config/navigation_panel.yml

[OO-FEATURE] Move template menu entry from Editorial to Administration

Move template menu entry

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/OrchestraView.coffee
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/widget/widgetChannel.coffee

[OO-BUGFIX] Refresh navigation menu after a new element has been created in a list

Refresh navigation menu after creating a new element

---

BackofficeBundle/Resources/public/less/openorchestra.less
BackofficeBundle/Resources/public/less/template.less

[OO-BUGFIX] Fix css ie11 template and node contribution

fix ie11 template and node

---

Backoffice/Form/Type/Component/ColorPickerType.php
Backoffice/Tests/Form/Type/ColorPickerTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/coffee/extendView/showVideo.coffee

[OO-BUGFIX] Make the color picker working in all contexts

Place ColorPickerType in Components + Make it working again in the VideoBlock

---

Backoffice/NavigationPanel/Strategies/ContentTypeForContentPanelStrategy.php

[OO-BUGFIX] Fix searchable option of content type field
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1491
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/532

fix searchable contentType

---

BackofficeBundle/Resources/public/coffee/extendView/showVideo.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

[OO-BUGFIX] Fix color picker form type

Fix color Picker form type on both context : video block and standard form

---

Backoffice/Form/Type/Component/TinymceType.php
Backoffice/Tests/Form/Type/Component/ColorPickerTypeTest.php
Backoffice/Tests/Form/Type/Component/TinymceTypeTest.php
BackofficeBundle/Resources/config/form.yml

[OO-BUGFIX] Fix TinyMCE content display after form submission

Fix TinyMCE display after form submission

---

Backoffice/ValueTransformer/Strategies/ArrayToHtmlStringTransformer.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1507
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/174
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/535

Update ArrayToHtmlStringTransformer for oo_media_choice

---

BackofficeBundle/Resources/public/less/blocksIcon.less

[OO-BUGFIX] fix the display of the media block icon

fix the display of the media block icon

---

BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1513
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/176

fix translation question

---

Backoffice/Form/Type/Component/DefaultListableCheckboxType.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Tests/Form/Type/Component/DefaultListableCheckboxTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-BUGFIX] Fix translation labels of defaultListable field in content type form

add translation for label of default listable

---

Backoffice/Form/Type/Component/ContentSearchType.php
Backoffice/Form/Type/Component/KeywordsChoiceType.php
Backoffice/Tests/Form/Type/Component/KeywordsChoiceTypeTest.php
BackofficeBundle/Resources/public/coffee/formBehavior/TagCreator.coffee

[OO-BUGFIX] Fix error 404 in the form keyword choice type when you create a new keyword

fix keyword choice type and contentSearchType

---

BackofficeBundle/Resources/public/coffee/contentType/TableViewAction.coffee
BackofficeBundle/Resources/public/coffee/table/TableChannel.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewAction.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-FEEATURE] When a content type is navigation menu is refresh

refresh menu when a content type is deleted

---

Backoffice/Form/Type/Component/RoleChoiceType.php
Backoffice/Tests/Form/Type/Component/RoleChoiceTypeTest.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/role_parameter.yml
BackofficeBundle/Resources/public/less/role.less
BackofficeBundle/Resources/translations/role.en.yml
BackofficeBundle/Resources/translations/role.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
GruntTasks/Targets/concat.orchestra_css.js
LogBundle/DependencyInjection/Compiler/RoleCompilerPass.php
LogBundle/DependencyInjection/OpenOrchestraLogExtension.php
LogBundle/Resources/config/role_parameter.yml
LogBundle/Resources/translations/role.en.yml
LogBundle/Resources/translations/role.fr.yml
UserAdminBundle/DependencyInjection/Compiler/RoleCompilerPass.php
UserAdminBundle/DependencyInjection/OpenOrchestraUserAdminExtension.php
UserAdminBundle/Resources/config/role_parameter.yml
UserAdminBundle/Resources/translations/role.en.yml
UserAdminBundle/Resources/translations/role.fr.yml

[OO-FEATURE] increase ergo fo group form
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1522
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/91
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/181

increase ergo for group form

---

BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/webSite/WebSiteFormView.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-FEATURE] refresh the page after website creation to show it in the fiexed top nav list

refresh page after website creation

---

ApiBundle/Transformer/RoleTransformer.php
Backoffice/Security/Authorization/Voter/DeleteRoleVoter.php
Backoffice/Tests/Security/Authorization/Voter/DeleteRoleVoterTest.php
Backoffice/Tests/UsageFinder/RoleUsageFinderTest.php
Backoffice/UsageFinder/RoleUsageFinder.php
BackofficeBundle/Resources/config/usage_finder.yml
BackofficeBundle/Resources/config/voter.yml

[OO-FEATURE] add voter on role usage
[OO-BUGFIX] fix error on role delete
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/94
https://github.com/open-orchestra/open-orchestra-model-interface/pull/171
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/92
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1530

Add role voter

---

BackofficeBundle/Resources/public/coffee/page/TemplateFormView.coffee

[OO-BUBFIX] Refresh template when edit template form is submitted

resfreh template after edit it

---

ApiBundle/Controller/AreaController.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Functional/Controller/AreaControllerTest.php
ApiBundle/Tests/Transformer/AreaTransformerTest.php
ApiBundle/Transformer/AreaTransformer.php
Backoffice/Manager/NodeManager.php

[OO-BUGFIX] Unused blocks are now definitivly suppressed from DB when deleted from a node and used no more
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1540
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/542
https://github.com/open-orchestra/open-orchestra-model-interface/pull/173

1.1 Physically remove deleted blocks

---

Backoffice/EventSubscriber/AreaCollectionSubscriber.php
Backoffice/Form/Type/AbstractAreaContainerType.php
Backoffice/Form/Type/AreaType.php
Backoffice/Form/Type/NodeType.php
Backoffice/Form/Type/TemplateType.php
Backoffice/Tests/EventSubscriber/AreaCollectionSubscriberTest.php
Backoffice/Tests/Form/Type/AreaTypeTest.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
Backoffice/Tests/Form/Type/TemplateTypeTest.php
Backoffice/Validator/Constraints/UniqueAreaIdValidator.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/validation/area.yml
BackofficeBundle/Resources/public/coffee/addPrototype.coffee
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

[OO-FEATURE] enhance area form in template, node and area

Optimize area form prototype

---

Backoffice/Tests/Validator/Constraints/CheckMainAliasPresenceTest.php
Backoffice/Tests/Validator/Constraints/CheckMainAliasPresenceValidatorTest.php
Backoffice/Validator/Constraints/CheckMainAliasPresence.php
Backoffice/Validator/Constraints/CheckMainAliasPresenceValidator.php
BackofficeBundle/Resources/config/validation/site.yml
BackofficeBundle/Resources/translations/validators.de.yml
BackofficeBundle/Resources/translations/validators.en.yml
BackofficeBundle/Resources/translations/validators.fr.yml

[OO-FEATURE] test on mandatory main alias in site form

Add main alias constraint

---

ApiBundle/Transformer/AreaTransformer.php

[OO-BUGFIX] Fix transform area from another site as the current site

fix transform area with an other site than current site

---

BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/195
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1546

1.1 Add a new trigger to tag a form-group with class has-error

---

Backoffice/Security/Authorization/Voter/DeleteNodeVoter.php
Backoffice/Tests/Security/Authorization/Voter/DeleteNodeVoterTest.php
BackofficeBundle/Resources/config/voter.yml
BackofficeBundle/Resources/public/coffee/groupTree/NodeTreeElementView.coffee

[OO-FEATURE] Adding voter to forbid removing node root

remove delete node root

---

Backoffice/EventSubscriber/NodeTemplateSelectionSubscriber.php
Backoffice/Tests/EventListener/UpdateStatusableElementCurrentlyPublishedFlagListenerTest.php
BackofficeBundle/DependencyInjection/Compiler/RoleCompilerPass.php

https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/77
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1562
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/26
https://github.com/open-orchestra/open-orchestra-libs/pull/44
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/551
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/96

Remove unused uses

---

BackofficeBundle/Resources/views/Tree/tree-macros.html.twig

[OO-MISC] Hide addpage button if no root page

remove addpage button if no root page

---

BackofficeBundle/Resources/views/BackOffice/Underscore/Jarvis/header._tpl.twig

[OO-FEATURE] Remove full screen for jarvis widget

Remove full screen option

---

BackofficeBundle/Resources/views/BackOffice/Underscore/dashboard/widget/abstract/abstractWidgetListView._tpl.twig

[OO-BUGFIX] Remove cursor move of dashboard widgets

fix dashboard widget remove sortable

---

Backoffice/Tests/ValueTransformer/Strategies/DoubleToHtmlStringTransformerTest.php
Backoffice/ValueTransformer/Strategies/DoubleToHtmlStringTransformer.php
BackofficeBundle/Resources/config/value_transformer.yml

[OO-BUGFIX] Fix transform correctly a type double in a string value.

fix transform string value type double

---

GroupBundle/Resources/config/validation/group.yml

[OO-BUGFIX] Add constraint Unique on group

fix error uniq index group

---

Backoffice/Form/Type/Component/RoleChoiceType.php
Backoffice/Tests/Form/Type/Component/RoleChoiceTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/role_parameter.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-BCBREAK] ``openOrchestra\Backoffice\Form\Type\ComponentRoleChoiceType`` take an array of role collector in parameter.
[OO-FEATURE] ``openOrchestra\Backoffice\Form\Type\ComponentRoleChoiceType`` can display roles of multiple role collector
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/552
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1567

Add role front in group

---

BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Underscore/elementTitle._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/widgetVersion._tpl.twig

[OO-FEATURE]  Add modification date for versions into global page and node.

Add modif date version

---

BackofficeBundle/Tests/Functional/Controller/NodeControllerTest.php

Change test with new roles order.
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/548
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/95
.https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1566

Change test node with new roles order

---

UserAdminBundle/DataFixtures/MongoDB/LoadUserSuperAdminData.php
UserAdminBundle/Event/UserFacadeEvent.php
UserAdminBundle/EventSubscriber/UserGroupsSubscriber.php
UserAdminBundle/Form/Type/UserType.php
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml
UserAdminBundle/Tests/EventSubscriber/UserGroupsSubscriberTest.php
UserAdminBundle/Tests/Form/Type/UserTypeTest.php
UserAdminBundle/Tests/Functional/Controller/FormUserSuperAdminControllersTest.php
UserAdminBundle/Transformer/UserTransformer.php

[OO-FEATURE] Remove choice groups  in edit user if the user is super admin
[OO-FEATURE] Remove role super admin of user admin in production fixture
[OO-BCBREAK] `` OpenOrchestra\UserAdminBundle\Event\UserFacadeEvent`` take a new argument `user` which is the user transformed
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1572
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/99

Hide choice group if super admin

---

Backoffice/EventSubscriber/BlockTypeSubscriber.php
Backoffice/EventSubscriber/ContentSearchSubscriber.php
Backoffice/Form/Type/Component/ContentSearchType.php
Backoffice/GenerateForm/Strategies/ConfigurableContentStrategy.php
Backoffice/Tests/EventSubscriber/ContentSearchSubscriberTest.php
Backoffice/Tests/Form/Type/Component/ContentSearchTypeTest.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RefreshForm.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
BackofficeBundle/Tests/Functional/EventSubscriber/BlockTypeSubscriberTest.php

Most of functionalities work. Three issue : error on refresh content search, refresh form on submit, properties mapped false recorder.
Temporary PR. 
@betd-rcarles 
[OO-FEATURE] add content search widget in configurable content block

Add content search configurable content

---

BackofficeBundle/Tests/Functional/Controller/EditNodeControllerTest.php

https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/97/files
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1571

Fix test with add voter workflow

---

BackofficeBundle/Tests/Command/OrchestraCheckConsistencyCommandTest.php

https://github.com/open-orchestra/open-orchestra-base-bundle/pull/80
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1580

fix test unit command

---

ApiBundle/Transformer/AreaTransformer.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/555
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1574

uncomment method deleteAreaFromBlock in area transformer

---

UserAdminBundle/EventSubscriber/UserGroupsSubscriber.php

[OO-TAG] Add label option into FormType

add label option into form

---

ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
BackofficeBundle/Resources/public/coffee/page/NodeView.coffee

[OO-FEATURE] Remove edit button for tranverse page

Remove edit button for transverse page

---

UserAdminBundle/Controller/Admin/UserController.php

[OO-BUGFIX] add constraints for email user unicity
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/97

change group constraints

---

BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-MISC] Rename navigation menu status and Role
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1589
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/102

Rename left menu

---

BackofficeBundle/Resources/public/coffee/page/NodeFormView.coffee

[OO-BUGFIX] Refresh node view when edit form of node  is submitted

refresh node when submit edit form

---

Backoffice/Form/Type/NodeType.php
Backoffice/NavigationPanel/Strategies/TransverseNodePanelStrategy.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Include/NavigationPanel/Menu/Editorial/transverseNode.html.twig
BackofficeBundle/Resources/views/Tree/tree-macros.html.twig
BackofficeBundle/Tests/Functional/Controller/HomepageControllerTest.php
BackofficeBundle/Tests/Functional/Controller/NodeControllerTest.php

[OO-FEATURE] Adding attribute ``boLabel`` on Node , used to generate tree in the Back Office
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1586
https://github.com/open-orchestra/open-orchestra-model-interface/pull/179
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/561

use bo label in navigation strategies

---

Backoffice/Security/Authorization/Voter/NodeVersionVoter.php
Backoffice/Tests/Security/Authorization/Voter/NodeVersionVoterTest.php

[OO-BUGFIX] Fix error access denied when select an other version node

fix error access denied when select other version node

---

ApiBundle/Controller/ControllerTrait/ListStatus.php
ApiBundle/Controller/NodeController.php
ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
BackofficeBundle/Resources/public/coffee/widget/StatusView.coffee
BackofficeBundle/Resources/views/BackOffice/Underscore/widgetStatus._tpl.twig

[OO-BUGFIX] Fix bug updating status of node with the update role of node of other type

fix update status role update other type node

---

ApiBundle/Transformer/NodeTransformer.php

[OO-BUGFIX] Fix access denied when edit node without ``role_access_site``

fix access denied when edit node without role_access_site

---

GroupBundle/Tests/Functional/Repository/GroupRepositoryTest.php
UserAdminBundle/DataFixtures/MongoDB/LoadUserData.php
UserAdminBundle/Tests/Functional/Repository/UserRepositoryTest.php

[OO-BUGFIX] create user with media folder access and create role for functional test
related PR
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/208

Add user folder create

---

BackofficeBundle/Resources/translations/messages.fr.yml

[OO-MISC] Corrected translation.
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/104
open-orchestra/open-orchestra-cms-bundle#1600

Translation corrected

---

ApiBundle/Facade/BlockFacade.php
ApiBundle/Tests/Transformer/BlockTransformerTest.php
ApiBundle/Transformer/BlockTransformer.php
BackofficeBundle/Resources/public/coffee/page/BlockView.coffee
BackofficeBundle/Resources/views/BackOffice/Underscore/blockView._tpl.twig

[OO-FEATURE] It is no longer possible to delete a block of global page if it is used
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1599
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/565

remove delete block in global page if used in other page

---

BackofficeBundle/Resources/public/coffee/formBehavior/RichText.coffee

[OO-BUGFIX] When you save multiple tinymce, there are saved correctly

save in textarea on change event tynmce

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee

[OO-BUGFIX] Fix error on field default value if field type is changed in content type form

fix reset default value when change field type

---

BackofficeBundle/Resources/public/less/template.less

[OO-BUGFIX] replace opacity by display in area toolbar to deactivate involuntary click

replace opacity by display for toolbar

---

Backoffice/Form/Type/BlockType.php
Backoffice/Tests/Form/Type/BlockTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/transformer.yml

[OO-BUGFIX] use dependency injection for BlockToArrayTransformer in BlockType

inject in BlockType BlockToArrayTransformer

---

BackofficeBundle/Resources/config/field_type.yml
BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee

[OO-BUGFIX] Fix default field in content type form

fix default field in content type form

---

BackofficeBundle/Controller/AbstractEditionRoleController.php
BackofficeBundle/Controller/AreaController.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/Controller/NodeController.php

[OO-BUGFIX] Fix block edition right management in global page

fix global block edition granted

---

BackofficeBundle/Controller/AbstractEditionRoleController.php
BackofficeBundle/Controller/AreaController.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/Controller/NodeController.php

[OO-BUGFIX] Fix block edition right management in globa page

1.1 fix global block edition

---

BackofficeBundle/Resources/public/coffee/page/NodeLayoutButtonView.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-FEATURE] Show node language and version language in title of edit form

add version and language form node

---

ApiBundle/Controller/RoleController.php
ApiBundle/Tests/Functional/Controller/ApiControllersSecurityTest.php
GroupBundle/EventSubscriber/NodeGroupRoleTransformSubscriber.php

[OO-FEATURE] Add a method to find role for node only.

change regex for node role

---

BackofficeBundle/Resources/public/coffee/webSite/WebSiteFormView.coffee

[OO-BUGFIX] Refresh page when saving a website form after a form error

refresh page when edit page

---

BackofficeBundle/Resources/public/less/tab.less
BackofficeBundle/Resources/views/BackOffice/Underscore/tabView._tpl.twig

[OO-FEATURE] Update css style of componement tab view replace class ``nav-tabs`` by ``nav-pills nav-justified``

update style tab view

---

BackofficeBundle/Resources/public/coffee/addPrototype.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/AbstractFormBehavior.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/FormLibraryBehavior.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RichText.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee

[OO-BUGFIX] fix tinymce issues in collection context

fix tinymce issues in collection context

---

ApiBundle/Controller/RoleController.php
ApiBundle/Tests/Functional/Controller/ApiControllersSecurityTest.php
GroupBundle/EventSubscriber/NodeGroupRoleTransformSubscriber.php

[OO-FEATURE] Add a method to find role for node only.

Regex node role 1.1

---

BackofficeBundle/Resources/public/less/tab.less
BackofficeBundle/Resources/views/BackOffice/Underscore/tabView._tpl.twig

[OO-FEATURE] Update css style of componement tab view replace class nav-tabs by nav-pills nav-justified

update style tab view 1.1

---

BackofficeBundle/Resources/public/coffee/webSite/WebSiteFormView.coffee

[OO-BUGFIX] Refresh page when saving a website form after a form error

Refresh page when edit website 1.1

---

BackofficeBundle/Resources/public/coffee/table/TableviewCollectionView.coffee

[OO-BUFGIX] Show breadcrumb after refresh page with datatable

fix show breadcrumb refrest page with datatable

---

composer.json

[OO-BUGFIX] maximun version for nodejs is ~4.4.3
[OO-FEATURE] Update requirement version of bower to 1.7
[OO-FEATURE] Update requirement version of grunt-cli ~1.2
[OO-FEATURE] Update requirement version of grunt-contrib-symlink ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-cssmin ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-coffee ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-uglify ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-concat ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-watch ~1.0
[OO-FEATURE] Update requirement version of grunt-contrib-clean ~1.0
[OO-FEATURE] Update requirement version of coffee-script ~1.10.0
[OO-FEATURE] Update requirement version of load-grunt-tasks ~3.5.0
[OO-FEATURE] Update …

fix nodejs version

---

BackofficeBundle/Resources/public/coffee/dataTable/plugins/InputFullPagination.coffee

[OO-BUGFIX] Fix the javascript error on datatable pagination

fix pagintation datatable pages undefined

---

GroupBundle/DataFixtures/MongoDB/AbstractLoadGroupData.php
GroupBundle/DataFixtures/MongoDB/LoadGroupDemoData.php
GroupBundle/Tests/Functional/Repository/GroupRepositoryTest.php

[OO-FEATURE] add an admin group that contains all role

admin group with all role

---

UserAdminBundle/DependencyInjection/Compiler/RoleUsageCompilerPass.php
UserAdminBundle/OpenOrchestraUserAdminBundle.php

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/102
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1645

move RoleUsage compiler pass in user admin bundle

---

Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

[OO-BUGFIX] Fix error index blocks when duplicate a node

fix index block when duplicate node

---

Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

[OO-BUGFIX] Fix error index blocks when duplicate a node

fix index block when duplicate node 1.1

---

Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

[OO-BUGFIX] Add boLabel on root node when create a new website
https://github.com/open-orchestra/open-orchestra-model-interface/pull/182
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1652

fix bo label

---

composer.json

[OO-MISC] Fix composer dependencies versions

fix dependencies versions

---

Backoffice/Form/Type/FieldTypeType.php
Backoffice/Tests/Form/Type/FieldTypeTypeTest.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

Order the fields of the contentType Form

order fields of contentType form

---

BackofficeBundle/Resources/public/less/contentTypeForm.less
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

[OO-BUGFIX] fix contentTypeForm to allow field type modification

fix content type form for content type

---

BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-BUGFIX] Fix french translations
cherry-pick: https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1666

Fix translations and put back homogeneity between 'en' and 'fr' keys.

---

ApiBundle/Controller/SiteController.php
ApiBundle/Transformer/NodeTransformer.php

[OO-FEATURE] FIlter language tabs on node page to show only languages used in a SiteAlias

FIlter language tabs on node page to show only languages used in a SiteAlias

---

BackofficeBundle/Controller/UnderscoreTemplateController.php
BackofficeBundle/Resources/public/coffee/underscoreTemplateLoader.coffee

[OO-BUGFIX] Fix loop redirection when load template underscore without valid session

fix load tempalte underscore wiithout session

---

Backoffice/GenerateForm/Strategies/ConfigurableContentStrategy.php
BackofficeBundle/Resources/public/coffee/formBehavior/ValidateHidden.coffee
BackofficeBundle/Resources/public/less/smartadminPatches/form.less
BackofficeBundle/Resources/public/less/tokenInputPatches/token.less

[OO-BUGFIX] A form containing a required oo_content_search now correctly display an error message when trying to submit it without completing the oo_content_search

Fix the content search form type when required

---

Backoffice/GenerateForm/Strategies/ConfigurableContentStrategy.php
BackofficeBundle/Resources/public/coffee/formBehavior/ValidateHidden.coffee
BackofficeBundle/Resources/public/less/smartadminPatches/form.less
BackofficeBundle/Resources/public/less/tokenInputPatches/token.less

[OO-BUGFIX] A form containing a required oo_content_search now correctly display an error message when trying to submit it without completing the oo_content_search

1 1 fix content search form type

---

GroupBundle/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriber.php

[OO-BUGFIX] Throw an exception in UpdateNodeGroupRoleMoveNodeSubscriber if NodeGroupRole is not set

Throw an exception in UpdateNodeGroupRoleMoveNodeSubscriber if NodeGroupRole is not set

---

GroupBundle/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriber.php

[OO-BUGFIX] Throw an exception in UpdateNodeGroupRoleMoveNodeSubscriber if NodeGroupRole is not set

1 1 update node subscriber exception

---

Backoffice/Security/Authorization/Voter/NodeVersionVoter.php
Backoffice/Tests/Security/Authorization/Voter/NodeVersionVoterTest.php

[OO-BUGFIX] Fix Backoffice/Security/Authorization/Voter/NodeVersionVoter when create a new node

fix node version voter

---

BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RefreshForm.coffee

[OO-BUGFIX] Fix refresh and submit configurable content block form

fix configurable content submit and refresh

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee

[OO-BUGFIX] Fix submit and content type select

fix catch js error

---

BackofficeBundle/Resources/public/less/template.less

[OO-BUGFIX] Fix IE9 padding of area in node and contribution in empty area

fix ie9 area padding and height

---

GroupBundle/EventSubscriber/NodeGroupRoleForGroupSubscriber.php
GroupBundle/Tests/EventSubscriber/NodeGroupRoleForGroupSubscriberTest.php

[OO-BUGFIX] Fix duplicate model group role when update on model group role

fix duplicate model group role when update group

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/InternalLinkFormView.coffee
BackofficeBundle/Resources/public/coffee/OrchestraModalView.coffee
BackofficeBundle/Resources/public/coffee/OrchestraView.coffee
BackofficeBundle/Resources/public/coffee/addPrototype.coffee
BackofficeBundle/Resources/public/coffee/backboneRouter.coffee
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RefreshForm.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RichText.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/formChannel.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-BUGFIX] Fix deactivate and re activate tinymce
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/240
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1706

Enable tiny mce reload

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/coffee/InternalLinkFormView.coffee
BackofficeBundle/Resources/public/coffee/OrchestraModalView.coffee
BackofficeBundle/Resources/public/coffee/OrchestraView.coffee
BackofficeBundle/Resources/public/coffee/addPrototype.coffee
BackofficeBundle/Resources/public/coffee/backboneRouter.coffee
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RefreshForm.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/RichText.coffee
BackofficeBundle/Resources/public/coffee/formBehavior/formChannel.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-BUGFIX] Fix deactivate and re activate tinymce
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/241
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1708

1.1 enable tiny mce reload

---

BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee

cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1714

fix change field type content type

---

ApiBundle/Controller/AreaController.php
ApiBundle/Facade/AreaCollectionFacade.php
ApiBundle/Tests/Transformer/AreaTransformerTest.php
ApiBundle/Transformer/AreaTransformer.php
BackofficeBundle/Resources/public/coffee/page/AreaView.coffee
BackofficeBundle/Resources/public/coffee/page/BlockView.coffee
BackofficeBundle/Resources/views/BackOffice/Underscore/areaView._tpl.twig

[OO-BUGFIX] a block only used in a single place can now be moved into another area without being deleted

1 1 fix move block

---

ApiBundle/Controller/AreaController.php
ApiBundle/Facade/AreaCollectionFacade.php
ApiBundle/Tests/Transformer/AreaTransformerTest.php
ApiBundle/Transformer/AreaTransformer.php
BackofficeBundle/Resources/public/coffee/page/AreaView.coffee
BackofficeBundle/Resources/public/coffee/page/BlockView.coffee
BackofficeBundle/Resources/views/BackOffice/Underscore/areaView._tpl.twig

[OO-BUGFIX] a block only used in a single place can now be moved into another area without being deleted

1 2 fix move block

---

ApiBundle/Transformer/ContentCollectionTransformer.php

[OO-BUGFIX] hide add button if user d'ont have create content role
https://github.com/open-orchestra/open-orchestra-cms-bundle/issues/1690

hide add button if user d'ont have create content role

---

BackofficeBundle/Resources/translations/role.en.yml
BackofficeBundle/Resources/translations/role.fr.yml

[OO-BUGFIX] Fix wrong translation on workflow rights in group administration
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1722
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/115

Fix misleading workflow role translations

---

BackofficeBundle/Resources/public/coffee/formBehavior/ValidateHidden.coffee

[OO-BUGFIX] Fix some broken input

Fix broken css on some input text

---

Backoffice/Model/GroupInterface.php
GroupBundle/Document/Group.php
GroupBundle/EventSubscriber/NodeGroupRoleForGroupSubscriber.php

[OO-BUGFIX] Clear the node per node rights when changing the binding between a group and a site

Clear the node per node rights when changing the binding between a group and a site

---

BackofficeBundle/Resources/public/coffee/page/NodeView.coffee
BackofficeBundle/Resources/public/coffee/page/TemplateView.coffee

[OO-BUGFIX] Fix areas order on local storage decache

fix area order on local storage decache

---

Backoffice/Form/Type/Component/ContentSearchType.php
Backoffice/Form/Type/Component/MultiLanguagesTextType.php
Backoffice/Tests/Form/Type/Component/ContentSearchTypeTest.php
Backoffice/Tests/Form/Type/MultiLanguagesTextTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

[OO-FEATURE] Add the oo_mullti_languages_text form type

Add MultiLanguagesTextType

---

BackofficeBundle/Resources/public/coffee/addPrototype.coffee

[OO-BUGFIX] Remove override default value of choice in javascript

fix default value choice

---

ApiBundle/Controller/NodeController.php
ApiBundle/Exceptions/HttpException/AccessLanguageForNodeNotGrantedHttpException.php
ApiBundle/Resources/translations/messages.en.yml
ApiBundle/Resources/translations/messages.fr.yml

[OO-BUGFIX] Disallow creation of node in a language belonging fronts languages but not current site aliases languages

control language before creating corresponding node

---

BackofficeBundle/Resources/public/coffee/setUpCallAjax.coffee
BackofficeBundle/Resources/public/coffee/widget/DuplicateView.coffee
BackofficeBundle/Resources/views/BackOffice/Underscore/widgetDuplicate._tpl.twig

[OO-BUGFIX] Fix popin error when click on button duplicate version

fix popin if error when click on button new version

---

Backoffice/EventSubscriber/ContentTypeSubscriber.php
Backoffice/Form/DataTransformer/ChoicesOptionToArrayTransformer.php
Backoffice/Tests/EventSubscriber/ContentTypeSubscriberTest.php
Backoffice/Tests/Form/DataTransformer/ChoicesOptionToArrayTransformerTest.php

[OO-BUGFIX] Fix data normalization when submitting a content form

fix norm data when submit content form

---

GroupBundle/EventListener/UpdateNodeGroupRoleListener.php
GroupBundle/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriber.php
GroupBundle/Tests/EventListener/UpdateNodeGroupRoleListenerTest.php
GroupBundle/Tests/EventSubscriber/UpdateNodeGroupRoleMoveNodeSubscriberTest.php

[OO-BUGFIX] Fix exception on node role list update in group when node contains deleted

exclude removed node from group update action

---

BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

[OO-BUGFIX] Fix the display of active tab of translated value form
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/issues/114

fix display translated value

---

BackofficeBundle/Resources/public/coffee/viewConfigurator.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-BUGFIX] Change the appConfigurationView creation order

Create the OrchestraViewConfigurator before dom:ready (#1762)

---

Backoffice/Form/DataTransformer/CsvToReferenceKeywordTransformer.php
BackofficeBundle/Resources/public/less/smartadminPatches/form.less

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1783
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/608

Fix transform keywords

---

BackofficeBundle/Resources/config/role_parameter.yml

[OO-BUG] Fixing of category of item template in the right form

 fix category item template in right form

---

BackofficeBundle/Resources/config/role_parameter.yml

[OO-BUG] Fixing of category of item template in the right form
cherry-pick https://github.com/open-orchestra/open-orchestra-docs/pull/202

fix category item template in right form (#1788)

---

composer.json

[OO-FEATURE] Move GeneratorBundle requirement from dev to standard
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1794
https://github.com/open-orchestra/open-orchestra/pull/985
https://github.com/open-orchestra/open-orchestra-front-demo/pull/251
https://github.com/open-orchestra/open-orchestra-media-demo/pull/116

Move GeneratorBundle requirement from dev to standard

---

Backoffice/Form/Type/FieldTypeType.php
Backoffice/Tests/Form/Type/FieldTypeTypeTest.php

[OO-BUGFIX] Fix dependency of modelBundle in class fieldTypeType

remove dependency of modelBundle in class fieldTypeType

---

Backoffice/EventSubscriber/BlockFormTypeSubscriber.php
Backoffice/Form/Type/BlockType.php
Backoffice/Tests/EventSubscriber/BlockFormTypeSubscriberTest.php

[OO-BUFGIX] Fix fill label block form

Fix label form

---

Backoffice/Form/Type/FieldTypeType.php
Backoffice/Tests/Form/Type/FieldTypeTypeTest.php

[OO-BUGFIX] Fix dependency of modelBundle in class fieldTypeType
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1803

remove dependency of modelBundle in class fieldTypeType (#1803)

---

Backoffice/Tests/EventSubscriber/NodeThemeSelectionSubscriberTest.php
Backoffice/Tests/Initializer/TranslatedValueDefaultValueInitializerTest.php
Backoffice/Tests/Manager/AreaManagerTest.php
Backoffice/Tests/Manager/TranslationChoiceManagerTest.php
Backoffice/Tests/Validator/Constraints/UniqueNodeOrderTest.php
Backoffice/Tests/Validator/Constraints/UniqueNodeOrderValidatorTest.php
composer.json

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1802
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/51
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/267

remove unused require dev

---

Backoffice/EventSubscriber/ContentTypeTypeSubscriber.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Form/Type/FieldTypeType.php
Backoffice/Tests/EventSubscriber/ContentTypeTypeSubscriberTest.php
BackofficeBundle/Resources/public/less/smartadminPatches/form.less
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-FEATURE] Adding a more explicit message for field content type id and field id about allowed characters
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1809
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/615

add help text content type and field id illegal character

---

Backoffice/EventSubscriber/FieldOptionTypeSubscriber.php

[OO-FEATURE] The custom field types used to describe a Content Type can now be described with as many options as desired
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/270
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1815

Allow the total description of the fields option parameters in configuration

---

Backoffice/Form/Type/Component/InternalLinkType.php
Backoffice/Form/Type/Component/SiteSiteAliasType.php
Backoffice/Validator/Constraints/BooleanConditionValidator.php
BackofficeBundle/Controller/InternalLinkController.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/coffee/InternalLinkFormView.coffee
BackofficeBundle/Resources/public/coffee/tinyMCE/plugins/LinkOrchestraPlugin.coffee
BackofficeBundle/Resources/public/coffee/tinyMCE/tinyMceConf.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/translations/validators.de.yml
BackofficeBundle/Resources/translations/validators.en.yml
BackofficeBundle/Resources/translations/validators.fr.yml
BackofficeBundle/Resources/views/BackOffice/Underscore/internalLinkModalView._tpl.twig

[OO-FEATURE] add internal link functionality
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1816
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/236
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/186

Activate internal link

---

Backoffice/Manager/ContentManager.php
Backoffice/Tests/Manager/ContentManagerTest.php

[OO-BUGFIX] Fix currently published when a published content is duplicate

fix set currently publish to false when duplicate published content

---

Backoffice/Form/Type/NodeType.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Controller/NodeController.php

[OO-BUGFIX] Removing boLabel of the error nodes
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1822
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/620

remove bo label in error node

---

ApiBundle/Controller/ContentController.php

[OO-BUGFIX] Fix elements count in content pagination.
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1825
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/623
https://github.com/open-orchestra/open-orchestra-model-interface/pull/213
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1829
https://github.com/open-orchestra/open-orchestra/pull/1001

fix list content with filter site id

---

Backoffice/Form/Type/NodeType.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Controller/NodeController.php

[OO-BUGFIX] Removing boLabel of the error nodes
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1822
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1828
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/622

remove bo label in error node (#1822)

---

Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php

[OO-MISC] optimize route generation on node update
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1818
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/618
https://github.com/open-orchestra/open-orchestra-model-interface/pull/210

Optimize route creation

---

Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php

[OO-MISC] optimize route generation on node update

1.1 optimize route creation

---

Backoffice/Form/Type/Component/RoleChoiceType.php
Backoffice/Tests/Form/Type/Component/RoleChoiceTypeTest.php
BackofficeBundle/Resources/config/role_parameter.yml
LogBundle/Resources/config/role_parameter.yml
UserAdminBundle/Resources/config/role_parameter.yml

[OO-FEATURE] add possibility to order role in group form by yml configuration
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1830
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/271
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/144

order role in group form

---

BackofficeBundle/Resources/public/coffee/dashboard/widget/abstract/AbstractWidgetListView.coffee
BackofficeBundle/Resources/public/coffee/setUpCallAjax.coffee

[OO-BUGFIX] Fix redirecting to dashboard when clicking in navigation after login

fix redirect to dashboard after login

---

Backoffice/Security/Authorization/Voter/NodeGroupRoleVoter.php
Backoffice/Tests/Security/Authorization/Voter/NodeGroupRoleVoterTest.php

[OO-BUGFIX] Fixed slowness when show node tree, Optimized NodeGroupRoleVoter

optimized NodeGroupRoleVoter

---

Backoffice/Security/Authorization/Voter/NodeGroupRoleVoter.php
Backoffice/Tests/Security/Authorization/Voter/NodeGroupRoleVoterTest.php

[OO-BUGFIX] Fixed slowness when show node tree, Optimized NodeGroupRoleVoter
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1836

optimized NodeGroupRoleVoter (#1836)

---

ApiBundle/Transformer/GroupTransformer.php
BackofficeBundle/Resources/public/coffee/dataTable/DataTableView.coffee
BackofficeBundle/Resources/public/coffee/group/GroupUserList.coffee
BackofficeBundle/Resources/public/coffee/group/TableUserListActionView.coffee
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Underscore/group/groupUserList._tpl.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/group/tableUserListAction._tpl.twig
GruntTasks/Targets/concat.orchestra_js.js
UserAdminBundle/Controller/Api/UserController.php
UserAdminBundle/DependencyInjection/Configuration.php
UserAdminBundle/EventSubscriber/GroupUserListTransformSubscriber.php
UserAdminBundle/Facade/UserListGroupCollectionFacade.php
UserAdminBundle/Facade/UserListGroupFacade.php
UserAdminBundle/Resources/config/subscriber.yml
UserAdminBundle/Resources/config/transformer.yml
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml
UserAdminBundle/Tests/EventSubscriber/GroupUserListTransformSubscriberTest.php
UserAdminBundle/Transformer/UserListGroupCollectionTransformer.php
UserAdminBundle/Transformer/UserListGroupTransformer.php

[OO-FEATURE] Add posibility to add an user in group edit display
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/122
https://github.com/open-orchestra/open-orchestra/pull/1009
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1837

Add tab group user list

---

Backoffice/Model/GroupInterface.php
GroupBundle/Document/Group.php
GroupBundle/Migrations/MongoDB/Version20160808142956.php

[OO-BUGFIX] Optimized access of model group role

add key in model groupe role storage

---

Backoffice/Model/GroupInterface.php
GroupBundle/Document/Group.php
GroupBundle/Migrations/MongoDB/Version20160808142956.php

[OO-BUGFIX] Optimized access of model group role
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1839

add key in model groupe role storage (#1839)

---

Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1840
https://github.com/open-orchestra/open-orchestra-model-interface/pull/214
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/630
https://github.com/open-orchestra/open-orchestra/pull/1014

add language in parameter for route generation

---

BackofficeBundle/Resources/public/coffee/backboneRouter.coffee
BackofficeBundle/Resources/public/coffee/orchestraLib.coffee
BackofficeBundle/Resources/public/coffee/user/LoadPersonnalAccountRoute.coffee
BackofficeBundle/Resources/public/coffee/user/LoadUserInfoRoute.coffee
BackofficeBundle/Resources/public/less/smartadminPatches/nav.less
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/BackOffice/Include/NavigationPanel/userInfo.html.twig
BackofficeBundle/Resources/views/BackOffice/Underscore/backToList._tpl.twig
GruntTasks/Targets/concat.orchestra_js.js
UserAdminBundle/Controller/Admin/UserController.php
UserAdminBundle/Form/Type/UserType.php
UserAdminBundle/Tests/Form/Type/UserTypeTest.php

[OO-FEATURE] In the Back Office, users can now update their account via the new "My account page"

1 2 user pref

---

Backoffice/EventSubscriber/ContentTypeOrderFieldSubscriber.php
Backoffice/Form/Type/FieldTypeType.php
Backoffice/Tests/EventSubscriber/ContentTypeOrderFieldSubscriberTest.php
Backoffice/Tests/Form/Type/FieldTypeTypeTest.php
BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/Resources/config/subscriber.yml
BackofficeBundle/Resources/public/coffee/ContentTypeFormView.coffee
BackofficeBundle/Resources/public/less/contentTypeForm.less
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

[OO-FEATURE] Added possibility to order the fields of content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1842
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/631
https://github.com/open-orchestra/open-orchestra-model-interface/pull/215

Add order content type field

---

ApiBundle/Transformer/StatusTransformer.php
Backoffice/EventSubscriber/ContentTypeOrderFieldSubscriber.php
Backoffice/EventSubscriber/NodeThemeSelectionSubscriber.php
Backoffice/EventSubscriber/SiteSubscriber.php
BackofficeBundle/Resources/config/authorize_status_change.yml
BackofficeBundle/StrategyManager/AuthorizeStatusChangeManager.php
BackofficeBundle/Tests/StrategyManager/AuthorizeStatusChangeManagerTest.php

[OO-BUGFIX]  Authorize status update when user is super admin

authorize status update when user is super admin

---

ApiBundle/Transformer/StatusTransformer.php
Backoffice/EventSubscriber/NodeThemeSelectionSubscriber.php
Backoffice/EventSubscriber/SiteSubscriber.php
BackofficeBundle/Resources/config/authorize_status_change.yml
BackofficeBundle/StrategyManager/AuthorizeStatusChangeManager.php
BackofficeBundle/Tests/StrategyManager/AuthorizeStatusChangeManagerTest.php

[OO-BUGFIX]  Authorize status update when user is super admin
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1849

Status upadte check if super admin11

---

composer.json

[OO-MISC] Update requirement of stfalcon/tinymce-bundle to `~1.1.0`

update stfalcon tinymce

---

Backoffice/GenerateForm/Strategies/TinyMCEWysiwygStrategy.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-display-bundle/pull/239
https://github.com/open-orchestra/open-orchestra-model-interface/pull/218
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/635
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/53
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1852

add default parameter block form searchable

---

ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Transformer/ContentTransformerTest.php
ApiBundle/Transformer/ContentTransformer.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Manager/ContentManager.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
Backoffice/Tests/Manager/ContentManagerTest.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-FEATURE] optional version for content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1859
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/639
https://github.com/open-orchestra/open-orchestra-model-interface/pull/221
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/49

optional version for content

---

ApiBundle/Controller/GroupController.php
ApiBundle/Transformer/GroupTransformer.php
ApiBundle/Transformer/NodeTransformer.php
Backoffice/Model/GroupInterface.php
GroupBundle/Document/Group.php
GroupBundle/Tests/Document/GroupTest.php

[OO-FEATURE] Add possibility to duplicate a group in the group list

add posibility to duplicate a group

---

Backoffice/EventSubscriber/UpdateNodesThemeSubscriber.php
Backoffice/Tests/EventSubscriber/UpdateNodesThemeSubscriberTest.php
BackofficeBundle/Controller/ThemeController.php
BackofficeBundle/Resources/config/subscriber.yml

[OO-BUGFIX] When theme is updated, modification is updated in node
https://github.com/open-orchestra/open-orchestra-front-demo/pull/282
https://github.com/open-orchestra/open-orchestra/pull/1026
https://github.com/open-orchestra/open-orchestra-model-interface/pull/222
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/640
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1860

upate node theme when theme name is upadted

---

Backoffice/EventSubscriber/ContentUpdateCacheSubscriber.php
Backoffice/Form/Type/StatusType.php
Backoffice/Security/Authorization/Voter/StatusableVoter.php
Backoffice/Tests/EventSubscriber/ContentUpdateCacheSubscriberTest.php
Backoffice/Tests/Form/Type/StatusTypeTest.php
Backoffice/Tests/Security/Authorization/Voter/StatusableVoterTest.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php

[OO-FEATURE] add possibility to create status published and editable
https://github.com/open-orchestra/open-orchestra-model-interface/pull/226
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/644
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1867

add possiblity to have published and editable status

---

ApiBundle/Facade/ContentAttributeFacade.php
ApiBundle/Handler/ContentAttributeValueHandler.php
ApiBundle/Resources/config/services.yml
ApiBundle/Tests/Handler/ContentAttributeValueHandlerTest.php
ApiBundle/Transformer/ContentAttributeTransformer.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/config/field_type.yml

[OO-FEATURE] Possibility to deserialize the value of content attribute
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1866
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/283

add deserialize content attribute value

---

ApiBundle/Facade/StatusFacade.php
ApiBundle/Transformer/StatusTransformer.php
Backoffice/Form/Type/NodeType.php
Backoffice/Form/Type/StatusType.php
Backoffice/Manager/NodePublisher.php
Backoffice/Manager/NodePublisherInterface.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
Backoffice/Tests/Form/Type/StatusTypeTest.php
Backoffice/Tests/Manager/NodePublisherTest.php
BackofficeBundle/Command/OrchestraPublishNodeCommand.php
BackofficeBundle/Command/OrchestraUnpublishNodeCommand.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Resources/config/auto_publisher.yml
BackofficeBundle/Resources/config/datatable_parameter.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/Command/OrchestraPublishNodeCommandTest.php
BackofficeBundle/Tests/Command/OrchestraUnpublishNodeCommandTest.php

[OO-FEATURE] Nodes can now be auto-published/unpublished on date 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1845
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/634
https://github.com/open-orchestra/open-orchestra-model-interface/pull/217
https://github.com/open-orchestra/open-orchestra-provision/pull/40
https://github.com/open-orchestra/open-orchestra-docs/pull/230
https://github.com/open-orchestra/open-orchestra/pull/1028

1.2 auto publishing

---

Backoffice/EventSubscriber/ContentUpdateCacheSubscriber.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Form/Type/StatusType.php
Backoffice/Tests/EventSubscriber/ContentUpdateCacheSubscriberTest.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
Backoffice/Tests/Form/Type/StatusTypeTest.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-FEATURE] add optionally statusable for content
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1869
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/646
https://github.com/open-orchestra/open-orchestra-model-interface/pull/227

add optionally statusable

---

.travis.yml
BackofficeBundle/Resources/public/coffee/dataTable/header/DataTableViewSearchHeader.coffee
BackofficeBundle/Resources/public/coffee/groupTree/NodeTreeElementView.coffee
BackofficeBundle/Resources/public/coffee/page/area/AreaView.coffee
BackofficeBundle/Resources/public/coffee/page/node/NodeView.coffee

[OO-MISC] Optimization loading of underscore templates for the node and the list view
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1880
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1879
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/288
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/287

optimize load template node and list view

---

Backoffice/Reference/Strategies/ContentInNodeReferenceStrategy.php
Backoffice/Tests/Reference/Strategies/ContentInNodeReferenceStrategyTest.php
BackofficeBundle/Resources/config/reference.yml

[OO-FEATURE] Content usage in configurable content block is now tracked
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1875
https://github.com/open-orchestra/open-orchestra-model-interface/pull/228
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/647

Track Content usage in Configurable content block

---

Backoffice/EventSubscriber/UpdateReferenceSubscriber.php
Backoffice/Tests/Reference/Strategies/AbstractReferenceStrategyTest.php
Backoffice/Tests/Reference/Strategies/ContentInNodeReferenceStrategyTest.php
Backoffice/Tests/Reference/Strategies/KeywordInContentReferenceStrategyTest.php
Backoffice/Tests/Reference/Strategies/KeywordInContentTypeReferenceStrategyTest.php
Backoffice/Tests/Reference/Strategies/KeywordInNodeReferenceStrategyTest.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/291
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1882

Refacto reference strategy tests to inject entityId

---

ApiBundle/Controller/ContentTypeController.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Transformer/ContentTypeTransformer.php

[OO-FEATURE] A content type can no more be deleted if it is used
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1885
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/649
https://github.com/open-orchestra/open-orchestra-model-interface/pull/230

A content type can no more be deleted if used

---

BackofficeBundle/DependencyInjection/Configuration.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1877
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1876

fix configuration field type search node

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/NodeController.php
ApiBundle/Controller/StatusController.php
ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Tests/Transformer/StatusTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
ApiBundle/Transformer/StatusTransformer.php

[OO-MISC] Greatly reduce the generation time of some node facades and status facades by muting some expansives attributes when not required by the context of the call

1-2 opti node api

---

ApiBundle/Exceptions/TransformerParameterTypeException.php
Backoffice/EventSubscriber/AbstractModulableTypeSubscriber.php
Backoffice/EventSubscriber/BlockTypeSubscriber.php
Backoffice/Form/DataTransformer/EmbedKeywordsToKeywordsTransformer.php
Backoffice/Tests/EventSubscriber/BlockTypeSubscriberTest.php
BackofficeBundle/StrategyManager/GenerateFormManager.php
BackofficeBundle/Tests/StrategyManager/GenerateFormManagerTest.php

https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/52
https://github.com/open-orchestra/open-orchestra-model-interface/pull/231
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/650
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/235
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/56
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1890
https://github.com/open-orchestra/open-orchestra-libs/pull/64

update deprecated annotation

---

BackofficeBundle/Resources/public/coffee/InternalLinkFormView.coffee

[OO-BUGFIX] fix space in form internal link context

fix error on space in internal link form

---

ApiBundle/Facade/ContentAttributeFacade.php
ApiBundle/Facade/DatatableCollectionParameterFacade.php
ApiBundle/Handler/ContentAttributeValueHandler.php
ApiBundle/Resources/config/services.yml
ApiBundle/Tests/Handler/ContentAttributeValueHandlerTest.php
ApiBundle/Transformer/ContentAttributeTransformer.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/config/field_type.yml

[OO-FEATURE] Possibility to deserialize the value of content attribute
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1887
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/294
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/107

add deserialize content

---

ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Transformer/BlockTransformerTest.php
ApiBundle/Transformer/BlockTransformer.php
Backoffice/DisplayBlock/Strategies/AddThisStrategy.php
Backoffice/DisplayBlock/Strategies/AudienceAnalysisStrategy.php
Backoffice/DisplayBlock/Strategies/ConfigurableContentStrategy.php
Backoffice/DisplayBlock/Strategies/ContactStrategy.php
Backoffice/DisplayBlock/Strategies/ContentListStrategy.php
Backoffice/DisplayBlock/Strategies/ContentStrategy.php
Backoffice/DisplayBlock/Strategies/FooterStrategy.php
Backoffice/DisplayBlock/Strategies/GmapStrategy.php
Backoffice/DisplayBlock/Strategies/LanguageListStrategy.php
Backoffice/DisplayBlock/Strategies/MenuStrategy.php
Backoffice/DisplayBlock/Strategies/SearchResultStrategy.php
Backoffice/DisplayBlock/Strategies/SearchStrategy.php
Backoffice/DisplayBlock/Strategies/SubMenuStrategy.php
Backoffice/DisplayBlock/Strategies/TinyMCEWysiwygStrategy.php
Backoffice/DisplayBlock/Strategies/VideoStrategy.php
BackofficeBundle/Resources/config/display.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1894
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/296

fix block transformer block private

---

BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php

[OO-MISC] Block Gmap and AddThis are disabled
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/656
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1895

Disable block gmap add this

---

BackofficeBundle/Resources/public/coffee/extendView/showVideo.coffee

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1897

fix block video change video type (#1897)

---

BackofficeBundle/Resources/views/Block/AudienceAnalysis/show.html.twig

cherry-pick
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1898

Fix add block analytics (#1898)

---

ApiBundle/Tests/Transformer/ContentTransformerTest.php
ApiBundle/Transformer/ContentTransformer.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Manager/ContentManager.php
Backoffice/Tests/Manager/ContentManagerTest.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-BUGFIX] Enhance non statusable and versionable in content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1899
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/147
https://github.com/open-orchestra/open-orchestra-model-interface/pull/234
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/658

enhance statusable content type interface

---

UserAdminBundle/Controller/Admin/UserController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1904
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/125

add validatio group constraint check password

---

UserAdminBundle/Controller/Admin/UserController.php

cherry pick 
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1904
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1909
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/126

add validatio group constraint check password (#1904)

---

BackofficeBundle/Resources/public/coffee/page/area/AreaView.coffee

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1903

fix multiple call reaload area (#1903)

---

Backoffice/EventSubscriber/RedirectionTypeSubscriber.php
Backoffice/Form/Type/Component/SiteChoiceType.php
Backoffice/Tests/EventSubscriber/RedirectionTypeSubscriberTest.php

[OO-BUGFIX] Fix save site name when redirection is saved.

fix site name redirection

---

Backoffice/EventSubscriber/RedirectionTypeSubscriber.php
Backoffice/Form/Type/Component/SiteChoiceType.php
Backoffice/Tests/EventSubscriber/RedirectionTypeSubscriberTest.php

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1908

fix site name redirection (#1908)

---

Backoffice/Repository/GroupRepositoryInterface.php
GroupBundle/Repository/GroupRepository.php

[OO-FEATURE] Add GroupRepository::findAllWithSiteId
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/298
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1907

Add GroupRepository::findAllWithSiteId

---

BackofficeBundle/Resources/public/coffee/user/LoadUserInfoRoute.coffee

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1912

wait localstorage , to add tab view (#1906)

---

Backoffice/Repository/GroupRepositoryInterface.php
GroupBundle/Repository/GroupRepository.php

[OO-FEATURE] Add GroupRepository::findAllWithSiteId
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/306
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1919

1.1 Add GroupRepository::findAllWithSiteId

---

Backoffice/EventSubscriber/UpdateReferenceSubscriber.php
Backoffice/Tests/EventSubscriber/UpdateReferenceSubscriberTest.php
BackofficeBundle/Resources/config/subscriber.yml

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1915

add reference whe a node or a content is updated (#1915)

---

ApiBundle/Controller/ContentController.php
ApiBundle/Controller/KeywordController.php
ApiBundle/Exceptions/HttpException/ContentNotDeletableException.php
ApiBundle/Exceptions/HttpException/KeywordNotDeletableException.php
ApiBundle/Resources/translations/messages.en.yml
ApiBundle/Transformer/ContentTransformer.php

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1914

remove posibility to remove a content used (#1914)

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/NodeController.php
ApiBundle/Controller/StatusController.php
ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Tests/Transformer/StatusTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
ApiBundle/Transformer/StatusTransformer.php

[OO-MISC] Greatly reduce the generation time of some node facades and status facades by muting some expansives attributes when not required by the context of the call

1.1 Refacto NodeTransformer + Add AREAS + PREVIEW groups

---

ApiBundle/Controller/ControllerTrait/HandleRequestDataTable.php
ApiBundle/Controller/TrashcanController.php
Backoffice/EventSubscriber/AbstractDeleteSubscriber.php
LogBundle/Controller/LogController.php
LogBundle/Repository/LogRepositoryInterface.php

[OO-FEATURE] add possibility to pre-filter data in table view (use case, filter on current site for trashcan)
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1916
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/661
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/54
https://github.com/open-orchestra/open-orchestra-libs/pull/65
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/108
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/150
https://github.com/open-orchestra/open-orchestra/pull/1047

add site on trash item

---

ApiBundle/Controller/ControllerTrait/HandleRequestDataTable.php
ApiBundle/Controller/TrashcanController.php
Backoffice/EventSubscriber/AbstractDeleteSubscriber.php
LogBundle/Controller/LogController.php
LogBundle/Repository/LogRepositoryInterface.php

[OO-FEATURE] add possibility to pre-filter data in table view (use case, filter on current site for trashcan)

1.2 add site trash item

---

BackofficeBundle/Resources/public/coffee/log/TableConfiguration.coffee
BackofficeBundle/Resources/public/coffee/table/TableNoLinksviewCollectionView.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewCollectionView.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-FEATURE] hide action button in log datatable

hide action button in log datatable

---

BackofficeBundle/Resources/public/coffee/log/TableConfiguration.coffee
BackofficeBundle/Resources/public/coffee/table/TableNoLinksviewCollectionView.coffee
BackofficeBundle/Resources/public/coffee/table/TableviewCollectionView.coffee
GruntTasks/Targets/concat.orchestra_js.js

[OO-FEATURE] hide action button in log datatable

1.2 hide action log

---

BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/coffee/forbiddenAccessRedirection.coffee
UserAdminBundle/Controller/Admin/UserController.php

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1926#issuecomment-251968355

fix forbidden self edit user password (#1926)

---

LogBundle/Resources/config/datatable_parameter.yml

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1924

hide search field log message (#1924)

---

Backoffice/EventSubscriber/ContentSearchSubscriber.php
Backoffice/Form/Type/Component/ContentChoiceType.php
Backoffice/Tests/EventSubscriber/ContentSearchSubscriberTest.php
Backoffice/Tests/Form/Type/Component/ContentChoiceTypeTest.php

[OO-BUGFIX] Content search filter content with the current site 
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-model-interface/pull/238
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/662
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1925

fix content search, add filter current site

---

Backoffice/EventSubscriber/ContentSearchSubscriber.php
Backoffice/Form/Type/Component/ContentChoiceType.php
Backoffice/Tests/EventSubscriber/ContentSearchSubscriberTest.php
Backoffice/Tests/Form/Type/Component/ContentChoiceTypeTest.php

[OO-BUGFIX] Content search filter content with the current site
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/246
https://github.com/open-orchestra/open-orchestra-model-interface/pull/242
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/664
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1932
cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1925

fix content search, add filter current site (#1925)

---

BackofficeBundle/Controller/AbstractAdminController.php
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee

[OO-FEATURE] add dedicated code error on form error
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1933
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/310

use new code error on form error

---

BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php

cherry pick 
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/656
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1895

disable block gmap and add this

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/SiteController.php
ApiBundle/Controller/ThemeController.php
ApiBundle/Facade/SiteFacade.php
ApiBundle/Transformer/SiteTransformer.php
ApiBundle/Transformer/ThemeTransformer.php

[OO-MISC] Optimize Site collection Api request

Optimize site collection api request

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/NodeController.php
ApiBundle/Facade/NodeFacade.php
ApiBundle/Transformer/NodeTransformer.php

[OO-MISC] Optimize node api requests

Go further with optimization of node api requests

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Facade/ContentTypeFacade.php
ApiBundle/Transformer/ContentTypeTransformer.php

[OO-MISC] Optimize Content type api requests

Optimize Content type api requests

---

BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee

cherry pick 9519ac7fc0f5b81e9d6e8b0df2ff149bf1965033

fix js code error (#1956)

---

ApiBundle/Controller/NodeController.php
ApiBundle/Exceptions/HttpException/NodeNotDeletableException.php
ApiBundle/Transformer/NodeTransformer.php
Backoffice/EventSubscriber/UpdateReferenceSubscriber.php
Backoffice/Reference/Strategies/AbstractKeywordReferenceStrategy.php
Backoffice/Reference/Strategies/ContentInNodeReferenceStrategy.php
Backoffice/Reference/Strategies/KeywordInContentReferenceStrategy.php
Backoffice/Reference/Strategies/KeywordInContentTypeReferenceStrategy.php
Backoffice/Reference/Strategies/KeywordInNodeReferenceStrategy.php
Backoffice/Reference/Strategies/NodeInNodeReferenceStrategy.php
Backoffice/Tests/Reference/Strategies/AbstractReferenceStrategyTest.php
Backoffice/Tests/Reference/Strategies/NodeInNodeReferenceStrategyTest.php
BackofficeBundle/Resources/config/reference.yml

[OO-FEATURE] Add use reference when node is used in node
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/247
https://github.com/open-orchestra/open-orchestra-model-interface/pull/243
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/60
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/667
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1934
https://github.com/open-orchestra/open-orchestra/pull/1053

add use reference node

---

Backoffice/EventSubscriber/ContentTypeStatusableSubscriber.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Tests/EventSubscriber/ContentTypeStatusableSubscriberTest.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/subscriber.yml

[OO-FEATURE] synchronize all contents with statusable state in content type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1966
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/677
https://github.com/open-orchestra/open-orchestra-model-interface/pull/247
https://github.com/open-orchestra/open-orchestra/pull/1073

add subscriber and update on statusable content type changing

---

Backoffice/EventSubscriber/ContentTypeStatusableSubscriber.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Tests/EventSubscriber/ContentTypeStatusableSubscriberTest.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/subscriber.yml

[OO-FEATURE] synchronize all contents with statusable state in content type
https://github.com/open-orchestra/open-orchestra/pull/1074
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1970
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/681
https://github.com/open-orchestra/open-orchestra-model-interface/pull/249

1.2 add statusable subscriber

---

ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Transformer/BlockTransformerTest.php
ApiBundle/Transformer/BlockTransformer.php

[OO-BUGFIX] Fix set fixed parameter defined in default configuration when a block is created

Fix set default configuration fixed parameter block

---

ApiBundle/Transformer/BlockTransformer.php
Backoffice/Form/DataTransformer/BlockToArrayTransformer.php
Backoffice/Form/Type/BlockType.php
Backoffice/Form/Type/Component/TemplateSetType.php
Backoffice/Form/Type/NodeType.php
Backoffice/GenerateForm/Strategies/AddThisStrategy.php
Backoffice/GenerateForm/Strategies/AudienceAnalysisStrategy.php
Backoffice/GenerateForm/Strategies/ConfigurableContentStrategy.php
Backoffice/GenerateForm/Strategies/ContactStrategy.php
Backoffice/GenerateForm/Strategies/ContentListStrategy.php
Backoffice/GenerateForm/Strategies/ContentStrategy.php
Backoffice/GenerateForm/Strategies/GmapStrategy.php
Backoffice/GenerateForm/Strategies/LoginStrategy.php
Backoffice/GenerateForm/Strategies/SearchResultStrategy.php
Backoffice/GenerateForm/Strategies/SearchStrategy.php
Backoffice/GenerateForm/Strategies/SubMenuStrategy.php
Backoffice/GenerateForm/Strategies/TinyMCEWysiwygStrategy.php
Backoffice/GenerateForm/Strategies/VideoStrategy.php
Backoffice/Manager/TemplateManager.php
Backoffice/Tests/Form/DataTransformer/BlockToArrayTransformerTest.php
Backoffice/Tests/Form/Type/BlockTypeTest.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/config/services.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

[OO-FEATURE] add special page for node, tabulation, fieldset and style for block
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1980
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/60
https://github.com/open-orchestra/open-orchestra-model-interface/pull/251

Add special page

---

BackofficeBundle/Controller/AbstractAdminController.php
BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Model/Form.js

[OO-BUGFIX] Use correct code for form submission error

change returned error code on form submission

---

BackofficeBundle/Resources/public/coffee/extendView/submitAdmin.coffee

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1982

Fix checkvalidity html52.0

---

BackofficeBundle/DataFixtures/MongoDB/LoadNodeRouteDocumentData.php

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1984

fix load route document (#1984)

---

Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php
BackofficeBundle/Resources/config/services.yml

https://github.com/open-orchestra/open-orchestra/pull/1082
https://github.com/open-orchestra/open-orchestra-model-interface/pull/252
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/684
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1985

fix route document redirection when update site alias

---

Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php
BackofficeBundle/Resources/config/services.yml

cherry pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1985

fix route direction document when update site alias

---

ApiBundle/Controller/AreaController.php
ApiBundle/Facade/NodeFacade.php
ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Transformer/NodeTransformer.php
Backoffice/EventSubscriber/BlockFormTypeSubscriber.php
Backoffice/Form/DataTransformer/BlockToArrayTransformer.php
Backoffice/Form/Type/BlockType.php
Backoffice/Tests/Form/DataTransformer/BlockToArrayTransformerTest.php
Backoffice/Tests/Form/Type/BlockTypeTest.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/Resources/config/parameters.yml
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php

https://github.com/open-orchestra/open-orchestra/pull/1086
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1996
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/688

fix functional tests

---

Backoffice/Form/Type/Component/LanguageBySitesType.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/User/UserRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Header/HeaderView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NodeFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/User/UserFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/Loader.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/Manager.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/ScrollTable.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Model/Form.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/View/AbstractFormView.js
BackofficeBundle/Resources/public/less/theme/open-orchestra.less
BackofficeBundle/Resources/public/template/Header/headerView._tpl.html
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
BackofficeBundle/Resources/views/layout.html.twig
GruntTasks/Targets/concat.orchestra_js.js
UserAdminBundle/Controller/Admin/UserController.php
UserAdminBundle/EventSubscriber/UserGroupsSubscriber.php
UserAdminBundle/Form/Type/RegistrationUserType.php
UserAdminBundle/Form/Type/UserType.php
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml
UserAdminBundle/Tests/Form/Type/UserTypeTest.php

https://github.com/open-orchestra/open-orchestra/pull/1089
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/129
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1999

Expose user route

---

WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowFunctionDataFunctional.php
WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowFunctionDataProduction.php
WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowProfileDataFunctional.php
WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowRightDataFunctional.php
WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowrightDataProduction.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/695
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2012

Move workflow fixtures from model to cms

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Collection/OrchestraCollection.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/Mixin/UrlPaginateViewMixin.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/View/AbstractDataTableView.js
UserAdminBundle/Controller/Api/UserController.php
UserAdminBundle/Facade/UserCollectionFacade.php
UserAdminBundle/Resources/config/transformer.yml
UserAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/User/UserListView.js
UserAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/User/UsersView.js
UserAdminBundle/Transformer/UserCollectionTransformer.php
UserAdminBundle/Transformer/UserTransformer.php

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/134
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2020
https://github.com/open-orchestra/open-orchestra/pull/1103

Add remove user

---

ApiBundle/Controller/NodeController.php
Backoffice/Form/Type/Component/KeywordsChoiceType.php
Backoffice/Security/Authorization/Voter/AbstractEditorialVoter.php
Backoffice/Security/Authorization/Voter/AbstractVoter.php
Backoffice/Security/Authorization/Voter/ContentVoter.php
Backoffice/Security/Authorization/Voter/DeveloperToolVoter.php
Backoffice/Security/Authorization/Voter/NodeNotHydratedVoter.php
Backoffice/Security/Authorization/Voter/NodeVoter.php
Backoffice/Security/Authorization/Voter/PlatformAdministrationVoter.php
Backoffice/Security/Authorization/Voter/SiteAdministrationVoter.php
Backoffice/Security/Authorization/Voter/TrashItemVoter.php
Backoffice/Tests/Security/Authorization/Voter/ContentVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/DeveloperToolVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/NodeNotHydratedVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/NodeVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/PlatformAdministrationVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/SiteAdministrationVoterTest.php
Backoffice/Tests/Security/Authorization/Voter/TrashItemVoterTest.php
BackofficeBundle/Controller/NodeController.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Header/HeaderView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Header/SiteSelectorView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Navigation/NavigationView.js
BackofficeBundle/Resources/public/template/Navigation/navigationView._tpl.html
BackofficeBundle/Resources/public/template/Node/nodeElementTreeView._tpl.html
BackofficeBundle/Resources/views/layout.html.twig
LogBundle/Model/LogInterface.php
UserAdminBundle/Controller/Admin/UserController.php
UserAdminBundle/Controller/Api/UserController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2026
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/327

add voter entity type

---

ApiBundle/Facade/StatusFacade.php
ApiBundle/Tests/Transformer/NodeTransformerTest.php
ApiBundle/Tests/Transformer/StatusTransformerTest.php
ApiBundle/Transformer/StatusTransformer.php
Backoffice/EventListener/UpdateStatusableElementCurrentlyPublishedFlagListener.php
Backoffice/EventSubscriber/ContentUpdateCacheSubscriber.php
Backoffice/EventSubscriber/UpdateRedirectionNodeSubscriber.php
Backoffice/Form/Type/StatusType.php
Backoffice/Manager/NodeManager.php
Backoffice/Tests/EventListener/UpdateStatusableElementCurrentlyPublishedFlagListenerTest.php
Backoffice/Tests/EventSubscriber/ContentUpdateCacheSubscriberTest.php
Backoffice/Tests/EventSubscriber/UpdateRedirectionNodeSubscriberTest.php
Backoffice/Tests/EventSubscriber/UpdateRouteDocumentSubscriberTest.php
Backoffice/Tests/Manager/NodeManagerTest.php
Backoffice/Tests/Validator/Constraints/BlockNodePatternValidatorTest.php
Backoffice/Validator/Constraints/BlockNodePatternValidator.php
composer.json

[OO-MISC] Refacto status attributes
https://github.com/open-orchestra/open-orchestra/pull/1110
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2030
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/705
https://github.com/open-orchestra/open-orchestra-model-interface/pull/266

Refacto status attributes

---

Backoffice/EventSubscriber/NodeChoiceStatusSubscriber.php
Backoffice/Model/GroupInterface.php
Backoffice/Tests/EventSubscriber/NodeChoiceStatusSubscriberTest.php
Backoffice/Tests/Security/Authorization/Voter/AbstractVoterTest.php
BackofficeBundle/Resources/config/subscriber.yml
GroupBundle/Document/Group.php
Workflow/Security/Authorization/Voter/AbstractWorkflowVoter.php
Workflow/Security/Authorization/Voter/ContentWorkflowVoter.php
Workflow/Security/Authorization/Voter/NodeWorkflowVoter.php
Workflow/Tests/Security/Authorization/Voter/ContentWorkflowVoterTest.php
Workflow/Tests/Security/Authorization/Voter/NodeWorkflowVoterTest.php
WorkflowAdminBundle/DataFixtures/MongoDB/LoadWorkflowProfileDataFunctional.php
WorkflowAdminBundle/DependencyInjection/OpenOrchestraWorkflowAdminExtension.php
WorkflowAdminBundle/Resources/config/voter.yml

[OO-FEATURE] Add workflow voters
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2024
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/699
https://github.com/open-orchestra/open-orchestra-model-interface/pull/264
https://github.com/open-orchestra/open-orchestra/pull/1109
https://github.com/open-orchestra/open-orchestra-front-demo/pull/324

2 0 workflow voters

---

ApiBundle/Controller/SiteController.php
ApiBundle/Facade/SiteCollectionFacade.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Transformer/SiteCollectionTransformer.php
ApiBundle/Transformer/SiteTransformer.php
BackofficeBundle/Resources/public/config/navigation.json
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Collection/Site/Sites.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Site/SiteRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Site/SiteListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Site/SitesView.js
BackofficeBundle/Resources/public/template/Navigation/Configuration/site._tpl.html
BackofficeBundle/Resources/public/template/Site/sitesView._tpl.html
BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml
UserAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/User/UserListView.js

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/713
https://github.com/open-orchestra/open-orchestra-model-interface/pull/273
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2049
https://github.com/open-orchestra/open-orchestra/pull/1122

add list site

---

ApiBundle/Controller/SiteController.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Transformer/SiteTransformer.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Collection/Site/Sites.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Site/SiteListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Site/SitesView.js
BackofficeBundle/Resources/public/template/Site/sitesView._tpl.html

https://github.com/open-orchestra/open-orchestra-front-demo/pull/328
https://github.com/open-orchestra/open-orchestra/pull/1124
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2050
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/714
https://github.com/open-orchestra/open-orchestra-model-interface/pull/274

remove delete multiple sites

---

ApiBundle/Context/CMSGroupContext.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Facade/ContentTypeCollectionFacade.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Transformer/ContentTypeCollectionTransformer.php
ApiBundle/Transformer/ContentTypeTransformer.php
ApiBundle/Transformer/SiteCollectionTransformer.php
BackofficeBundle/Resources/public/config/navigation.json
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Collection/ContentType/ContentTypes.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/ContentType/ContentTypeRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/ContentType/ContentTypesListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/ContentType/ContentTypesView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/Mixin/DeleteCheckboxListViewMixin.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/View/AbstractCollectionView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/View/AbstractDataTableView.js
BackofficeBundle/Resources/public/template/ContentType/contentTypeEditView._tpl.html
BackofficeBundle/Resources/public/template/ContentType/contentTypesView._tpl.html
BackofficeBundle/Resources/public/template/Navigation/Developer/contentType._tpl.html
BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml
WorkflowAdminBundle/Resources/public/config/navigation.json

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2056
https://github.com/open-orchestra/open-orchestra-model-interface/pull/276
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/717
https://github.com/open-orchestra/open-orchestra/pull/1126

Add content type list

---

Backoffice/EventSubscriber/NodeTemplateSelectionSubscriber.php
Backoffice/Tests/EventSubscriber/NodeTemplateSelectionSubscriberTest.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/public/template/Form/Behavior/NodeTemplateSelection._tpl.html
BackofficeBundle/Resources/public/templateSet/default/test.html
UserAdminBundle/Controller/Api/UserController.php
WorkflowAdminBundle/Controller/Api/StatusController.php
WorkflowAdminBundle/Controller/Api/WorkflowProfileController.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/723
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2072

fix required template node

---

Backoffice/Manager/ClientConfigurationManager.php
Backoffice/Tests/Manager/ClientConfigurationManagerTest.php
BackofficeBundle/Controller/AdminController.php
BackofficeBundle/DependencyInjection/Compiler/ClientConfigurationCompilerPass.php
BackofficeBundle/OpenOrchestraBackofficeBundle.php
BackofficeBundle/Resources/config/manager.yml
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Context.js
BackofficeBundle/Resources/views/layout.html.twig
BackofficeBundle/Tests/DependencyInjection/Compiler/ClientConfigurationCompilerPassTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2087
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/340

add service to contains client configuration

---

WorkflowAdminBundle/Controller/Api/StatusController.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/729
https://github.com/open-orchestra/open-orchestra-model-interface/pull/286
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2088
https://github.com/open-orchestra/open-orchestra/pull/1141

fix list worklow list status

---

Backoffice/EventSubscriber/CreateMandatoryNodesSubscriber.php
Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2092
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/730

update name error node

---

BackofficeBundle/DependencyInjection/Compiler/ClientConfigurationCompilerPass.php
BackofficeBundle/DependencyInjection/Compiler/TwigGlobalsCompilerPass.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Content/CellFormatter/DateFormatter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Context.js
BackofficeBundle/Resources/views/layout.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2091
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/115
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/116

Add date formatter

---

Backoffice/GeneratePerimeter/GeneratePerimeterManager.php
Backoffice/GeneratePerimeter/Strategy/GeneratePerimeterStrategy.php
Backoffice/GeneratePerimeter/Strategy/NodeGeneratePerimeterStrategy.php
Backoffice/Tests/GeneratePerimeter/Strategy/NodeGeneratePerimeterStrategyTest.php
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
GroupBundle/Form/DataTransformer/GroupPerimeterTransformer.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Resources/translations/messages.en.yml
GroupBundle/Resources/translations/messages.fr.yml
GroupBundle/Tests/Form/DataTransformer/GroupPerimeterTransformerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2094
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/247
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/343

Add media folder to perimeter

---

ApiBundle/Controller/NodeController.php
Backoffice/Form/DataTransformer/FieldOptionTransformer.php
Backoffice/Form/Type/Component/ContentSearchType.php
Backoffice/Form/Type/Component/SiteSiteAliasType.php
Backoffice/Manager/NodeManager.php
Backoffice/Reference/Strategies/NodeInBlockReferenceStrategy.php
Backoffice/Tests/Manager/NodeManagerTest.php
Backoffice/Tests/Reference/Strategies/NodeInBlockReferenceStrategyTest.php
BackofficeBundle/Resources/config/reference.yml

https://github.com/open-orchestra/open-orchestra-display-bundle/pull/253
https://github.com/open-orchestra/open-orchestra/pull/1144
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/70
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/733
https://github.com/open-orchestra/open-orchestra-model-interface/pull/289
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2096

add use trackable node

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Model/Form.js

[OO-FEATURE] Add media edit view
https://github.com/open-orchestra/open-orchestra/pull/1145
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2097
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/344
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/248
https://github.com/open-orchestra/open-orchestra-media-file-bundle/pull/31

Update form.js to allow file upload

---

Backoffice/Form/Type/ContentType.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/View/AbstractDataTableView.js
BackofficeBundle/Resources/public/less/theme/open-orchestra.less

[OO-FEATURE] Media Choice Form Type
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2114
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/249
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/346
https://github.com/open-orchestra/open-orchestra/pull/1149

2 0 media type

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/TagSelect2.js
BackofficeBundle/Resources/public/less/libPatches/tokenInputPatches/token.less
BackofficeBundle/Resources/public/less/theme/open-orchestra.less
BackofficeBundle/Resources/public/less/theme/variables.less
BackofficeBundle/Resources/public/template/ContentType/contentTypesView._tpl.html
BackofficeBundle/Resources/public/template/Node/nodeEditView._tpl.html
BackofficeBundle/Resources/public/template/Node/nodeToolbarView._tpl.html
BackofficeBundle/Resources/public/template/Node/nodeView._tpl.html
BackofficeBundle/Resources/public/template/Redirection/redirectionsView._tpl.html
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
LogBundle/Resources/public/template/Log/logsView._tpl.html
UserAdminBundle/Resources/public/template/User/groupListModalView._tpl.html

corrections integration

---

ApiBundle/Tests/Transformer/ContentTransformerTest.php
ApiBundle/Transformer/ContentTransformer.php
BackofficeBundle/Controller/ContentController.php

https://trello.com/c/qhYRT7um/35-4-2-2-liste-de-contenu-voiture

Fix content list

---

BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml
GroupBundle/Resources/translations/interface.en.yml
GroupBundle/Resources/translations/interface.fr.yml
GroupBundle/Resources/translations/messages.fr.yml
LogBundle/Resources/translations/interface.en.yml
LogBundle/Resources/translations/interface.fr.yml
UserAdminBundle/Resources/translations/interface.en.yml
UserAdminBundle/Resources/translations/interface.fr.yml
WorkflowAdminBundle/Resources/translations/interface.en.yml
WorkflowAdminBundle/Resources/translations/interface.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2116
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/348

fix translations

---

Backoffice/Tests/Validator/Constraints/UniqueMainAliasValidatorTest.php
Backoffice/Validator/Constraints/CheckMainAliasPresenceValidator.php
Backoffice/Validator/Constraints/UniqueMainAliasValidator.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/737
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2118

fix site alias error

---

Backoffice/Form/Type/SiteType.php
Backoffice/Manager/SiteManager.php
Backoffice/Tests/Manager/SiteManagerTest.php
BackofficeBundle/Resources/config/manager.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2124
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/738

remove add empty alias when new site is initialize

---

Backoffice/Manager/NodeManager.php
Backoffice/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/740
https://github.com/open-orchestra/open-orchestra-model-interface/pull/291
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2125
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/72

fix create new language node

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Tinymce/Plugins/OrchestraBBCode/OrchestraBBcodePlugin.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Tinymce/TinymceManager.js

[OO-FEATURE] Media in tinymce
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2129
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/350
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/251

Dump tinymce wysiwyg content to hidden textarea on presubmit

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NodesTreeView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Tree/AbstractTreeView.js

[OO-FEATURE] Add folder list view
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2090
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/246
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/342

Add AbstractTreeView

---

BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Block/NewSharedBlockFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/NewContentFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NewNodeFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Redirection/RedirectionFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Mixin/FormViewButtonsMixin.js
UserAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/User/NewUserFormView.js

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/739
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2126

fix dual alert in case of save and continue for content

---

BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php
GroupBundle/Form/DataTransformer/GroupRoleTransformer.php
GroupBundle/Form/Type/GroupRoleType.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Group/GroupFormView.js
GroupBundle/Tests/Form/DataTransformer/GroupRoleTransformerTest.php
GroupBundle/Tests/Form/Type/GroupRoleTypeTest.php
GroupBundle/Tests/Form/Type/GroupTypeTest.php
UserAdminBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/351
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2131

refresh group member list

---

ApiBundle/Controller/ContentController.php
BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Model/Content/Content.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Content/ContentRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/ConfirmModal/View/ConfirmModalView.js
BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml

https://github.com/open-orchestra/open-orchestra/pull/1158
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2136
https://github.com/open-orchestra/open-orchestra-model-interface/pull/294
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/745

add functionnality to  create content in new language

---

ApiBundle/Facade/FieldTypeFacade.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2135
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/744
https://github.com/open-orchestra/open-orchestra-model-interface/pull/293

remove unused field

---

BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2143
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/356
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/67

Fix broken blocks translations

---

BackofficeBundle/Resources/public/ecmascript/Lib/jquery.initialize.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/Tinymce.js

[OO-BUGFIX] Stop multiple listen of same DOM node appearence when saving a form

Auto suppression of event observed when dom node disappear

---

ApiBundle/Transformer/NodeTreeLeafTransformer.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Tree/AbstractTreeView.js
BackofficeBundle/Resources/public/less/theme/open-orchestra.less
BackofficeBundle/Resources/public/template/Node/nodeElementTreeView._tpl.html

[OO-BUGFIX] Drop on tree now correctly works on leafs
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2141
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/354

Nodes can be moved on leaf nodes

---

ApiBundle/Controller/ContentTypeController.php
BackofficeBundle/Controller/RedirectionController.php
GroupBundle/Controller/Admin/GroupController.php
GroupBundle/DataFixtures/MongoDB/LoadGroupData.php
WorkflowAdminBundle/Controller/Api/StatusController.php

[OO-BUGFIX] fix site admin rights
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2145
https://github.com/open-orchestra/open-orchestra/pull/1161

Fix s-admin rights

---

ApiBundle/Controller/SiteController.php
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml

[OO-BUGFIX] Fix login with few rights
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2146
https://github.com/open-orchestra/open-orchestra/pull/1162

Fix login with few rights

---

Backoffice/DisplayBlock/Strategies/AbstractDisplayBlockStrategy.php
UserAdminBundle/OAuth2/Strategy/ResourceOwnerPasswordGrantStrategy.php

[OO-REFACTO] Rename Abstract Stratgies
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/118
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2148
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/254
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/68
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/252
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/142

Rename Abstract Strategies

---

BackofficeBundle/Resources/views/layout.html.twig
GruntTasks/Targets/commands.assetic_dump.js
composer.json

[OO-MISC] Remove assetic
https://github.com/open-orchestra/open-orchestra/pull/1163
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/123
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2149
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/253

Remove assetic

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/Tinymce.js

[OO-BUGFIX] Fix disabled Rich text

Fix read only tinymce

---

ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Exceptions/HttpException/ContentTypeNotAllowedException.php
ApiBundle/Resources/translations/messages.en.yml
ApiBundle/Resources/translations/messages.fr.yml
Backoffice/Form/Type/BlockChoiceType.php
Backoffice/Form/Type/Component/ContentSearchType.php
Backoffice/Form/Type/Component/SiteContentTypeChoiceType.php
Backoffice/Form/Type/SiteType.php
Backoffice/Tests/Form/Type/Component/SiteContentTypeChoiceTypeTest.php
Backoffice/Tests/Form/Type/SiteTypeTest.php
BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2180
https://github.com/open-orchestra/open-orchestra-model-interface/pull/300
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/756

add content type choice on site form

---

Backoffice/Form/Type/NodeType.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/DependencyInjection/OpenOrchestraBackofficeExtension.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php
GroupBundle/Form/DataTransformer/GroupRoleTransformer.php
GroupBundle/Form/Type/GroupRoleType.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Resources/views/Form/form_div_layout.html.twig
GroupBundle/Tests/Form/DataTransformer/GroupRoleTransformerTest.php
GroupBundle/Tests/Form/Type/GroupRoleTypeTest.php
GroupBundle/Tests/Form/Type/GroupTypeTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2173
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/215
https://github.com/open-orchestra/open-orchestra-model-interface/pull/298
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/754
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/255

Add front group role

---

Backoffice/Form/DataTransformer/BlockToArrayTransformer.php
Backoffice/Form/Type/BlockType.php
Backoffice/Tests/Form/DataTransformer/BlockToArrayTransformerTest.php
Backoffice/Tests/Form/Type/BlockTypeTest.php
Backoffice/Tests/Validator/Constraints/UniqueBlockCodeTest.php
Backoffice/Tests/Validator/Constraints/UniqueBlockCodeValidatorTest.php
Backoffice/Validator/Constraints/UniqueBlockCode.php
Backoffice/Validator/Constraints/UniqueBlockCodeValidator.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/config/validation/site.yml
BackofficeBundle/Resources/config/validator.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/translations/validators.en.yml
BackofficeBundle/Resources/translations/validators.fr.yml
BackofficeBundle/Tests/DependencyInjection/OpenOrchestraBackofficeExtensionTest.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/758
https://github.com/open-orchestra/open-orchestra/pull/1173
https://github.com/open-orchestra/open-orchestra-model-interface/pull/302
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/218
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2199

Add code block

---

Backoffice/EventSubscriber/UpdateEmbeddedStatusSubscriber.php
Backoffice/Tests/EventSubscriber/UpdateEmbeddedStatusSubscriberTest.php
BackofficeBundle/Resources/config/subscriber.yml

https://github.com/open-orchestra/open-orchestra/pull/1175
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/759
https://github.com/open-orchestra/open-orchestra-model-interface/pull/303
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2200

add subscriber to update embedded status

---

ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Resources/config/transformer.yml
ApiBundle/Tests/Transformer/ContentTransformerTest.php
ApiBundle/Transformer/ContentTransformer.php
ApiBundle/Transformer/ContentTypeTransformer.php
Backoffice/Manager/ContentManager.php
Backoffice/Manager/NodeManager.php
Backoffice/Perimeter/Strategy/ContentTypePerimeterStrategy.php
Backoffice/Security/Authorization/Voter/AbstractEditorialVoter.php
Backoffice/Security/Authorization/Voter/AbstractPerimeterVoter.php
Backoffice/Security/Authorization/Voter/ContentVoter.php
Backoffice/Security/Authorization/Voter/SiteAdministrationVoter.php
Backoffice/Tests/Manager/ContentManagerTest.php
Backoffice/Tests/Manager/NodeManagerTest.php
Backoffice/Tests/Perimeter/Strategy/ContentTypePerimeterStrategyTest.php
Backoffice/Tests/Security/Authorization/Voter/ContentVoterTest.php
BackofficeBundle/Resources/config/manager.yml
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Context.js
BackofficeBundle/Resources/public/template/Content/summaryElementView._tpl.html
BackofficeBundle/Resources/public/template/Content/summaryView._tpl.html
BackofficeBundle/Resources/public/template/Menu/Contribution/content._tpl.html
BackofficeBundle/Resources/public/template/Menu/Contribution/trashcan._tpl.html
BackofficeBundle/Resources/public/template/Menu/menuView._tpl.html
BackofficeBundle/Resources/views/layout.html.twig

https://github.com/open-orchestra/open-orchestra/pull/1172
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/369
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2197

2 0 disable button when no rights

---

ApiBundle/Controller/NodeController.php
WorkflowAdminBundle/Controller/Api/StatusController.php
WorkflowAdminBundle/Exceptions/HttpException/StatusNotDeletableException.php
WorkflowAdminBundle/Resources/translations/messages.en.yml
WorkflowAdminBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra/pull/1179
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2208

refresh test

---

ApiBundle/Controller/NodeController.php

https://github.com/open-orchestra/open-orchestra-model-interface/pull/304
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/760
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2207
https://github.com/open-orchestra/open-orchestra/pull/1178

fix find node order

---

Backoffice/Form/Type/BlockType.php
Backoffice/Form/Type/NodeType.php
Backoffice/GenerateForm/Strategies/ContactStrategy.php
Backoffice/GenerateForm/Strategies/LoginStrategy.php
Backoffice/Tests/Form/Type/BlockTypeTest.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/template/Block/blockListComponentView._tpl.html
BackofficeBundle/Resources/public/template/Block/blockView._tpl.html
BackofficeBundle/Resources/public/template/Block/newBlockListAvailableView._tpl.html
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2223
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/219

hide input cache block node

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataTable/Mixin/UrlPaginateViewMixin.js

[OO-BUGFIX] Fix Back History on lists

Fix Back Button on lists

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentListView.js

[OO-BUGFIX] Fix content list on content without attribute

Fix content list on content without attribute

---

Backoffice/EventSubscriber/UpdateNodeSiteAliasSubscriber.php
Backoffice/Tests/EventSubscriber/UpdateNodeSiteAliasSubscriberTest.php
BackofficeBundle/Controller/SiteController.php
BackofficeBundle/DependencyInjection/Configuration.php
BackofficeBundle/Resources/config/subscriber.yml

https://github.com/open-orchestra/open-orchestra-model-interface/pull/305
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/761
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2229
https://github.com/open-orchestra/open-orchestra/pull/1189

add tree node on new site alias language

---

Backoffice/EventSubscriber/ContentTypeTypeSubscriber.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
BackofficeBundle/Controller/ContentTypeController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2235
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/764
https://github.com/open-orchestra/open-orchestra/pull/1192

2 0 fix first edition of content type

---

ApiBundle/Transformer/ContentTypeTransformer.php
Backoffice/Form/Type/ContentType.php
Backoffice/Manager/ContentManager.php
Backoffice/Tests/Form/Type/ContentTypeTest.php
Backoffice/Tests/Manager/ContentManagerTest.php
BackofficeBundle/Controller/ContentController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2233
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/762
https://github.com/open-orchestra/open-orchestra/pull/1190

fix new content out of workflow

---

ApiBundle/Controller/BlockController.php
ApiBundle/Controller/ContentController.php
ApiBundle/Controller/ContentTypeController.php
ApiBundle/Controller/KeywordController.php
ApiBundle/Controller/NodeController.php
ApiBundle/Transformer/ContentTransformer.php
ApiBundle/Transformer/ContentTypeTransformer.php
ApiBundle/Transformer/KeywordTransformer.php
ApiBundle/Transformer/NodeTransformer.php
Backoffice/BusinessRules/Strategies/BlockStrategy.php
Backoffice/BusinessRules/Strategies/BusinessActionInterface.php
Backoffice/BusinessRules/Strategies/ContentStrategy.php
Backoffice/BusinessRules/Strategies/ContentTypeStrategy.php
Backoffice/BusinessRules/Strategies/KeywordStrategy.php
Backoffice/BusinessRules/Strategies/NodeStrategy.php
Backoffice/Tests/BusinessRules/Strategies/BlockStrategyTest.php
Backoffice/Tests/BusinessRules/Strategies/ContentStrategyTest.php
Backoffice/Tests/BusinessRules/Strategies/ContentTypeStrategyTest.php
Backoffice/Tests/BusinessRules/Strategies/KeywordStrategyTest.php
Backoffice/Tests/BusinessRules/Strategies/NodeStrategyTest.php
BackofficeBundle/Controller/BlockController.php
BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Controller/NodeController.php
GroupBundle/BusinessRules/Strategies/GroupStrategy.php
GroupBundle/Controller/Api/GroupController.php
GroupBundle/Transformer/GroupTransformer.php
WorkflowAdminBundle/BusinessRules/Strategies/StatusStrategy.php
WorkflowAdminBundle/Controller/Admin/StatusController.php
WorkflowAdminBundle/Controller/Api/StatusController.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/379
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2244

Add business interface

---

WorkflowAdminBundle/Resources/config/subscriber.yml

|OO-BUGFIX] Fix wrong AddGroupWorkflowProfileSubscriber service definition

Fix wrong AddGroupWorkflowProfileSubscriber service definition

---

Backoffice/EventSubscriber/UpdateNodeSiteAliasSubscriber.php
Backoffice/GeneratePerimeter/GeneratePerimeterManager.php
Backoffice/GeneratePerimeter/Strategy/GeneratePerimeterStrategy.php
Backoffice/GeneratePerimeter/Strategy/GeneratePerimeterStrategyInterface.php
Backoffice/GeneratePerimeter/Strategy/NodeGeneratePerimeterStrategy.php
Backoffice/Tests/EventSubscriber/UpdateNodeSiteAliasSubscriberTest.php
Backoffice/Tests/GeneratePerimeter/GeneratePerimeterManagerTest.php
Backoffice/Tests/GeneratePerimeter/Strategy/NodeGeneratePerimeterStrategyTest.php
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
GroupBundle/Controller/Admin/GroupController.php
GroupBundle/Form/DataTransformer/GroupPerimeterTransformer.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Resources/config/generate_perimeter.yml
GroupBundle/Resources/config/transformer.yml
GroupBundle/Tests/Form/DataTransformer/GroupPerimeterTransformerTest.php
GroupBundle/Tests/Form/Type/GroupTypeTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2245
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/380

2 0 fix group perimeter on site

---

Backoffice/Form/Type/SiteType.php

https://github.com/open-orchestra/open-orchestra-front-bundle/pull/222
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2257
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/767

remove require meta author

---

BackofficeBundle/Resources/public/template/List/emptyListView._tpl.html

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/386
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2259

Update emptyList._tpl.html to allow title or button disabling

---

ApiBundle/Controller/NodeController.php
ApiBundle/Transformer/NodeCollectionTransformer.php
Backoffice/EventSubscriber/UpdateChildNodePathSubscriber.php
Backoffice/Manager/NodeManager.php
Backoffice/Repository/GroupRepositoryInterface.php
Backoffice/Tests/EventSubscriber/UpdateChildNodePathSubscriberTest.php
Backoffice/Tests/Manager/NodeManagerTest.php
BackofficeBundle/Resources/config/subscriber.yml
GroupBundle/Document/Perimeter.php
GroupBundle/EventSubscriber/GroupPerimeterSubscriber.php
GroupBundle/Repository/GroupRepository.php
GroupBundle/Resources/config/subscriber.yml
GroupBundle/Tests/EventSubscriber/GroupPerimeterSubscriberTest.php

[OO-BUGFIX] Update perimeters after a node or a folder has been moved
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2253
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/384
https://github.com/open-orchestra/open-orchestra-migration-bundle/pull/13
https://github.com/open-orchestra/open-orchestra-model-interface/pull/307

2 0 update perimeter on target move

---

Backoffice/EventSubscriber/SiteSubscriber.php
Backoffice/Form/Type/Component/InternalLinkType.php
Backoffice/Form/Type/Component/SiteSiteAliasType.php
Backoffice/Reference/Strategies/NodeInBlockReferenceStrategy.php
Backoffice/Tests/EventSubscriber/SiteSubscriberTest.php
Backoffice/Tests/Form/Type/Component/InternalLinkTypeTest.php
Backoffice/Tests/Form/Type/Component/SiteSiteAliasTypeTest.php
Backoffice/Tests/Reference/Strategies/NodeInBlockReferenceStrategyTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/PatchSubmit.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Tinymce/Plugins/InternalLink/InternalLinkPlugin.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Tinymce/Plugins/InternalLink/View/InternalLinkFormView.js
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2266
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/260

change wildcard administration in internal link form

---

Backoffice/TrashcanEntity/Strategies/TrashCanNodeStrategy.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2278
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/770
https://github.com/open-orchestra/open-orchestra-model-interface/pull/310
https://github.com/open-orchestra/open-orchestra/pull/1205

restore node under father

---

Backoffice/Tests/Validator/Constraints/UniqueBlockCodeValidatorTest.php
Backoffice/Validator/Constraints/UniqueBlockCodeValidator.php

https://github.com/open-orchestra/open-orchestra-front-bundle/pull/223
https://github.com/open-orchestra/open-orchestra-model-interface/pull/308
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/768
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2270

add site id block code validator

---

Backoffice/BusinessRules/Strategies/BusinessActionInterface.php
Backoffice/Repository/GroupRepositoryInterface.php
GroupBundle/Repository/GroupRepository.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2279
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/392
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/263

Add Groupepository::removeItemFromPerimeter

---

Backoffice/Tests/TrashcanEntity/TrashcanNodeStrategyTest.php
Backoffice/TrashcanEntity/Strategies/TrashCanNodeStrategy.php
GroupBundle/EventSubscriber/GroupPerimeterSubscriber.php
GroupBundle/Tests/EventSubscriber/GroupPerimeterSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2277
https://github.com/open-orchestra/open-orchestra-model-interface/pull/309

2 0 remove deleted node from perimeters

---

Backoffice/Manager/ContentTypeManager.php
Backoffice/Tests/Manager/ContentTypeManagerTest.php
BackofficeBundle/Resources/config/form.yml
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentsView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NodeListView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataFormatter/StatusFormatter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/ContentType.js
BackofficeBundle/Resources/public/less/theme/open-orchestra.less
BackofficeBundle/Resources/public/template/Content/contentsView._tpl.html
BackofficeBundle/Resources/public/template/Node/nodesView._tpl.html
BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2286
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/771

2 0 datatable default listable

---

Backoffice/EventSubscriber/UpdateRouteDocumentSubscriber.php
Backoffice/Manager/RouteDocumentManager.php
Backoffice/Tests/EventSubscriber/UpdateRouteDocumentSubscriberTest.php
Backoffice/Tests/Manager/RouteDocumentManagerTest.php

https://github.com/open-orchestra/open-orchestra/pull/1209
https://github.com/open-orchestra/open-orchestra-model-interface/pull/311
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/772
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2292

optimize create/delete route document

---

Backoffice/DisplayBlock/DisplayBlockInterface.php
Backoffice/DisplayBlock/DisplayBlockManager.php
Backoffice/DisplayBlock/Strategies/DefaultStrategy.php
Backoffice/DisplayBlock/Strategies/TinyMCEWysiwygStrategy.php
Backoffice/Tests/DisplayBlock/DisplayBlockManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2311
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/263
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/73

move method elastica

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Content/ContentRouter.js

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2288
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2315

Fix broken content summary route

---

ApiBundle/Controller/ContentController.php
Backoffice/EventListener/UpdateStatusableElementPublished.php
Backoffice/EventSubscriber/ContentTypeStatusableSubscriber.php
Backoffice/Form/Type/ContentType.php
Backoffice/Manager/ContentManager.php
Backoffice/Tests/EventListener/UpdateStatusableElementPublishedTest.php
Backoffice/Tests/EventSubscriber/ContentTypeStatusableSubscriberTest.php
Backoffice/Tests/Form/Type/ContentTypeTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2317
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/775
https://github.com/open-orchestra/open-orchestra/pull/1219

fix out of workflow

---

Backoffice/EventSubscriber/SiteSubscriber.php
Backoffice/Form/Type/Component/NodeChoiceType.php
Backoffice/Tests/EventSubscriber/SiteSubscriberTest.php
Backoffice/Tests/Form/Type/Component/NodeChoiceTypeTest.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/TreeChoice.js
BackofficeBundle/Resources/public/less/theme/open-orchestra.less

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2329
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/408
https://github.com/open-orchestra/open-orchestra/pull/1222
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/270

use new tree choice behavior

---

Backoffice/Form/Type/ContentType.php
Backoffice/Form/Type/ContentTypeType.php
Backoffice/Form/Type/NodeType.php
Backoffice/Tests/Form/Type/ContentTypeTest.php
Backoffice/Tests/Form/Type/ContentTypeTypeTest.php
Backoffice/Tests/Form/Type/NodeTypeTest.php
BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/Controller/NodeController.php
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml
BackofficeBundle/Resources/views/Form/form_div_layout.html.twig
GroupBundle/Controller/Admin/GroupController.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Resources/translations/messages.en.yml
GroupBundle/Resources/translations/messages.fr.yml
GroupBundle/Tests/Form/Type/GroupTypeTest.php
UserAdminBundle/Controller/Admin/UserController.php
Workflow/Form/Type/StatusType.php
Workflow/Tests/Form/Type/StatusTypeTest.php
WorkflowAdminBundle/Controller/Admin/StatusController.php
WorkflowAdminBundle/Resources/translations/messages.en.yml
WorkflowAdminBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/410
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2330

add messages business rule delete button

---

Backoffice/Tests/EventSubscriber/SiteSubscriberTest.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/271
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/412
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2332

fix test and dependency

---

BackofficeBundle/Resources/public/ecmascript/Lib/jquery.initialize.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Application.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Block/SharedBlockRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Content/ContentRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/Router/Node/NodeRouter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Block/SharedBlockFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Content/ContentsView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/ContentType/ContentTypesView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Header/HeaderView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Header/SiteSelectorView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Keyword/KeywordsView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Menu/MenuView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NewNodeTreeView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Node/NodesTreeView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Site/SiteFormView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/TrashItem/ContentRestoreModalView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/TrashItem/NodeRestoreModalView.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Context.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/DataFormatter/DateFormatter.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/DatePicker.js
GroupBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Group/GroupsView.js
UserAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Group/GroupListModalView.js
WorkflowAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Status/StatusesView.js
WorkflowAdminBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/WorkflowProfile/WorkflowProfilesView.js

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2337
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/416

add accessor for context

---

BackofficeBundle/Controller/ContentTypeController.php
BackofficeBundle/Resources/public/ecmascript/Lib/jquery.initialize.js
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Service/Form/Behavior/Tinymce.js

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2336
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/415

fix jquery initialize

---

BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/ContentType/ContentTypeFormView.js
GroupBundle/Controller/Admin/GroupController.php
GroupBundle/DataFixtures/MongoDB/LoadGroupData.php
GroupBundle/Document/Group.php
GroupBundle/Form/Type/GroupType.php
GroupBundle/Repository/GroupRepository.php
GroupBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/Group/GroupFormView.js
GroupBundle/Tests/Form/Type/GroupTypeTest.php
UserAdminBundle/Controller/Api/UserController.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2340
https://github.com/open-orchestra/open-orchestra/pull/1232
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/152

auto generate group name

---

Backoffice/EventSubscriber/UpdateChildNodePathSubscriber.php
Backoffice/Manager/NodeManager.php
Backoffice/Tests/EventSubscriber/UpdateChildNodePathSubscriberTest.php
Backoffice/Tests/Manager/NodeManagerTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2346
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/420
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/781
https://github.com/open-orchestra/open-orchestra-model-interface/pull/315
https://github.com/open-orchestra/open-orchestra/pull/1233

suppress recursive path

---

UserAdminBundle/Form/Type/UserType.php
UserAdminBundle/Resources/config/form.yml
UserAdminBundle/Resources/translations/messages.en.yml
UserAdminBundle/Resources/translations/messages.fr.yml
UserAdminBundle/Tests/Form/Type/UserTypeTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2342
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/153

locked user

---

BackofficeBundle/Controller/ContentController.php
BackofficeBundle/Resources/public/ecmascript/OpenOrchestra/Application/View/ContentType/ContentTypeFormView.js
BackofficeBundle/Resources/translations/interface.en.yml
BackofficeBundle/Resources/translations/interface.fr.yml
BackofficeBundle/Resources/translations/messages.en.yml
BackofficeBundle/Resources/translations/messages.fr.yml

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2350
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/78

fix content linked to site
