open-orchestra/open-orchestra-cms-bundle

- BackofficeBundle/EventSubscriber/ContentTypeSubscriber.php
When using a multiselect form field and the user does not select any value, the field is not posted by the browser. This case was not managed.
> fix content submission with multiselect field

- BackofficeBundle/Resources/public/coffee/FullPageFormView.coffee
If the FullPageFormView has multiple form in it, it will always submit the first one no matter what.
As we have direct access to the actually submitted form, I use it in the jQuery selector.
> fix form submission in FullPageFormView

- BackofficeBundle/DependencyInjection/Configuration.php
dump configuration : 
```
field_types:
field_name:
label:                ~ # Required
type:                 ~ # Required
default_value:
type:                 ~
options:
label:                ~
required:             true
options:
option_name:
default_value:        ~ # Required
options:
option_name:
type:                 ~ # Required
label:                ~ # Required
required:             true
```
> add configuration for field_type and options

- BackofficeBundle/Model/GroupInterface.php
- GroupBundle/Document/Group.php
- GroupBundle/EventListener/AddNodeGroupRoleForNodeListener.php
- GroupBundle/Tests/EventListener/AbstractNodeGroupRoleListenerTest.php
- GroupBundle/Tests/EventListener/AddNodeGroupRoleForNodeListenerTest.php
[OO-BUGFIX] When a node is duplicated there's no more node group role creation
> fix NodeGroupRole creation when it already exists

- BackofficeBundle/Resources/public/less/smartadminPatches/widget.less
[OO-BUGFIX] Fix jarvis widget header style in BackOffice
> fix jarvis widget css

- composer.json
[OO-CONFIGURATION] dependencies version are fixed : ``merge ~1.2.0``, ``backbone ~1.2.3``, ``jquery-minicolors ~2.2.3``, ``backbone.wreqr ~1.3.5``.
[OO-CONFIGURATION] bower dependency ``underscore`` is removed, this package is include by ``backbone``
> fix version backbone, wreqr, jquery-minicolors and merge

- BackofficeBundle/EventSubscriber/BlockTypeSubscriber.php
[OO-BUGFIX] Pass the 'disabled' option to the block form strategy when required
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1399
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/137
> Pass the 'disabled' option to the block form strategy when required

- Backoffice/DisplayBlock/Strategies/AddThisStrategy.php
- Backoffice/DisplayBlock/Strategies/AudienceAnalysisStrategy.php
- Backoffice/DisplayBlock/Strategies/ConfigurableContentStrategy.php
- Backoffice/DisplayBlock/Strategies/ContactStrategy.php
- Backoffice/DisplayBlock/Strategies/ContentListStrategy.php
- Backoffice/DisplayBlock/Strategies/ContentStrategy.php
- Backoffice/DisplayBlock/Strategies/FooterStrategy.php
- Backoffice/DisplayBlock/Strategies/GmapStrategy.php
- Backoffice/DisplayBlock/Strategies/LanguageListStrategy.php
- Backoffice/DisplayBlock/Strategies/LoginStrategy.php
- Backoffice/DisplayBlock/Strategies/MenuStrategy.php
- Backoffice/DisplayBlock/Strategies/SearchResultStrategy.php
- Backoffice/DisplayBlock/Strategies/SearchStrategy.php
- Backoffice/DisplayBlock/Strategies/SubMenuStrategy.php
- Backoffice/DisplayBlock/Strategies/TinyMCEWysiwygStrategy.php
- Backoffice/DisplayBlock/Strategies/VideoStrategy.php
[OO-BCBREAK] DisplayBundle/DisplayBlock/Strategies/AbstractStrategy:getCacheTags() is now abstract and must therefore be explicitally implemented on each display strategy
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/200
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/166
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/17
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/18
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/159
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/92
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1457
> Move getCacheTags from AbstractStrategy to implementing strategies

- BackofficeBundle/Resources/views/BackOffice/Include/NavigationPanel/show.html.twig
[OO-BUGFIX] In navigation panel, a root menu is hidden if these submenus aren't visible
> hide rootmenu if not submenu

- ApiBundle/Controller/NodeController.php
- Backoffice/NavigationPanel/Strategies/TreeNodesPanelStrategy.php
- Backoffice/Security/Authorization/Voter/StatusableVoter.php
- Backoffice/Tests/Security/Authorization/Voter/StatusableVoterTest.php
- BackofficeBundle/DependencyInjection/Compiler/RoleCompilerPass.php
- BackofficeBundle/Resources/translations/role.en.yml
- BackofficeBundle/Resources/translations/role.fr.yml
- BackofficeBundle/Resources/views/Tree/tree-macros.html.twig
- GroupBundle/DataFixtures/MongoDB/AbstractLoadGroupData.php
[OO-MISC] role ``ROLE_ACCESS_MOVE_NODE`` is renamed to ``ROLE_ACCESS_MOVE_TREE`` and is now a global role
> rename move tree

- BackofficeBundle/Resources/public/coffee/widget/previewLinkChannel.coffee
- BackofficeBundle/Resources/views/BackOffice/Underscore/widgetPreviewLink._tpl.twig
[OO-BUGFIX] hide the preview button on global pages (transverse)
> hide preview button on global pages

- BackofficeBundle/Resources/views/BackOffice/Underscore/widgetPreviewLink._tpl.twig
[OO-BUGFIX] fix indent after hide preview button on global pages
> add indent after hide preview button on global pages

- BackofficeBundle/Controller/ContentTypeController.php
[OO-BUGFIX] The event ``ContentTypeEvents::CONTENT_TYPE_UPDATE`` is dispatched only when content type form is valid
> send only when document is valid

- ApiBundle/Controller/NodeController.php
- Backoffice/EventSubscriber/CreateRootNodeSubscriber.php
- Backoffice/EventSubscriber/NodeTemplateSelectionSubscriber.php
- Backoffice/EventSubscriber/WebSiteNodeTemplateSubscriber.php
- Backoffice/Form/Type/SiteType.php
- Backoffice/Manager/NodeManager.php
- Backoffice/Tests/EventSubscriber/CreateRootNodeSubscriberTest.php
- Backoffice/Tests/EventSubscriber/NodeTemplateSelectionSubscriberTest.php
- Backoffice/Tests/EventSubscriber/WebSiteNodeTemplateSubscriberTest.php
- Backoffice/Tests/Form/Type/SiteTypeTest.php
- Backoffice/Tests/Manager/NodeManagerTest.php
- Backoffice/Tests/Manager/SiteManagerTest.php
- BackofficeBundle/Controller/NodeController.php
- BackofficeBundle/Controller/SiteController.php
- BackofficeBundle/Resources/config/form.yml
- BackofficeBundle/Resources/config/subscriber.yml
- BackofficeBundle/Resources/translations/messages.en.yml
- BackofficeBundle/Resources/translations/messages.fr.yml
[OO-DEPRECATED] ``initializeNewNode``  is deprecated and replace by ``initializeNode`` in class ``OpenOrchestra\Backoffice\Manager\NodeManager``. this method will be removed in 1.2.0
[OO-FEATURE] When a website is created, an homepage for this site is also created.
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1518
https://github.com/open-orchestra/open-orchestra-model-interface/pull/169
> create root note when site is created

- Backoffice/EventSubscriber/BlockMenuCacheSubscriber.php
- Backoffice/Tests/EventSubscriber/BlockMenuCacheSubscriberTest.php
- BackofficeBundle/Resources/config/form.yml
- BackofficeBundle/Resources/config/subscriber.yml
[OO-FEATURE] Block menu are invalidate when a node is removed, moved, restore and the status of a node changes .
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/205
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/75
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1531
> Block menu cache

- Backoffice/EventSubscriber/ChangeContentStatusSubscriber.php
- Backoffice/EventSubscriber/ContentTypeUpdateCacheSubscriber.php
- Backoffice/EventSubscriber/ContentUpdateCacheSubscriber.php
- Backoffice/Tests/EventSubscriber/ContentTypeUpdateCacheSubscriberTest.php
- Backoffice/Tests/EventSubscriber/ContentUpdateCacheSubscriberTest.php
- BackofficeBundle/Resources/config/subscriber.yml
[OO-DEPRECATED] class ``OpenOrchestra\Backoffice\EventSubscriber\ChangeContentStatusSubscriber`` s deprecated in 1.1.0 and will be removed in 1.2.0, it is replace by ContentUpdateCacheSubscriber
[OO-FEATURE] When a content is deleted or his status is updated tag ``'contentId-' . $contentId`` is invalidate.
[OO-FEATURE] When a content type is deleted or updated tag ``''contentType-' . $contentType`` is invalidate.
> invalidate tag when update content and content type

- BackofficeBundle/Resources/public/coffee/backboneRouter.coffee
- BackofficeBundle/Resources/views/BackOffice/Underscore/deleteButton._tpl.twig
If a page contains a cloned button we can not click this button after open a modal which contains a cloned button because the page loses focus. this PR fix that by using two instances: one for normal page and an other for modal page
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/199
> fix cloned save button

- ApiBundle/Exceptions/TransformerParameterTypeException.php
- ApiBundle/Tests/Transformer/BlockTransformerTest.php
- ApiBundle/Tests/Transformer/ContentAttributeTransformerTest.php
- ApiBundle/Tests/Transformer/ContentTransformerTest.php
- ApiBundle/Tests/Transformer/GroupTransformerTest.php
- ApiBundle/Tests/Transformer/ModelGroupRoleTransformerTest.php
- ApiBundle/Tests/Transformer/NodeTransformerTest.php
- ApiBundle/Tests/Transformer/StatusTransformerTest.php
- ApiBundle/Transformer/ApiClientTransformer.php
- ApiBundle/Transformer/AreaTransformer.php
- ApiBundle/Transformer/BlockTransformer.php
- ApiBundle/Transformer/ContentAttributeTransformer.php
- ApiBundle/Transformer/ContentTransformer.php
- ApiBundle/Transformer/ContentTypeTransformer.php
- ApiBundle/Transformer/FieldTypeTransformer.php
- ApiBundle/Transformer/GroupTransformer.php
- ApiBundle/Transformer/KeywordTransformer.php
- ApiBundle/Transformer/ModelGroupRoleTransformer.php
- ApiBundle/Transformer/NodeCollectionTransformer.php
- ApiBundle/Transformer/NodeTransformer.php
- ApiBundle/Transformer/RedirectionTransformer.php
- ApiBundle/Transformer/RoleStringTransformer.php
- ApiBundle/Transformer/RoleTransformer.php
- ApiBundle/Transformer/SiteTransformer.php
- ApiBundle/Transformer/StatusTransformer.php
- ApiBundle/Transformer/TemplateFlexTransformer.php
- ApiBundle/Transformer/TemplateTransformer.php
- ApiBundle/Transformer/ThemeTransformer.php
- ApiBundle/Transformer/TrashItemTransformer.php
[OO-BUFGIX] Fix dependency between BaseApi and ApiBundle, move TransformerParameterTypeException
[OO-DEPRECATED] The ``OpenOrchestra\ApiBundle\Exceptions\TransformerParameterTypeException`` class is deprecated since version 1.2.0 and will be removed in 1.3.0, use ``OpenOrchestra\BaseApi\Exceptions\TransformerParameterTypeException``
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/80
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/214
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1623
>  move TransformerParameterTypeException to base api bundle

- ApiBundle/Exceptions/TransformerParameterTypeException.php
- ApiBundle/Tests/Transformer/BlockTransformerTest.php
- ApiBundle/Tests/Transformer/ContentAttributeTransformerTest.php
- ApiBundle/Tests/Transformer/ContentTransformerTest.php
- ApiBundle/Tests/Transformer/GroupTransformerTest.php
- ApiBundle/Tests/Transformer/ModelGroupRoleTransformerTest.php
- ApiBundle/Tests/Transformer/NodeTransformerTest.php
- ApiBundle/Tests/Transformer/StatusTransformerTest.php
- ApiBundle/Transformer/ApiClientTransformer.php
- ApiBundle/Transformer/AreaTransformer.php
- ApiBundle/Transformer/BlockTransformer.php
- ApiBundle/Transformer/ContentAttributeTransformer.php
- ApiBundle/Transformer/ContentTransformer.php
- ApiBundle/Transformer/ContentTypeTransformer.php
- ApiBundle/Transformer/FieldTypeTransformer.php
- ApiBundle/Transformer/GroupTransformer.php
- ApiBundle/Transformer/KeywordTransformer.php
- ApiBundle/Transformer/ModelGroupRoleTransformer.php
- ApiBundle/Transformer/NodeCollectionTransformer.php
- ApiBundle/Transformer/NodeTransformer.php
- ApiBundle/Transformer/RedirectionTransformer.php
- ApiBundle/Transformer/RoleStringTransformer.php
- ApiBundle/Transformer/RoleTransformer.php
- ApiBundle/Transformer/SiteTransformer.php
- ApiBundle/Transformer/StatusTransformer.php
- ApiBundle/Transformer/TemplateFlexTransformer.php
- ApiBundle/Transformer/TemplateTransformer.php
- ApiBundle/Transformer/ThemeTransformer.php
- ApiBundle/Transformer/TrashItemTransformer.php
[OO-BUFGIX] Fix dependency between BaseApi and ApiBundle, move TransformerParameterTypeException
[OO-DEPRECATED] The ``OpenOrchestra\ApiBundle\Exceptions\TransformerParameterTypeException`` class is deprecated since version 1.2.0 and will be removed in 1.3.0, use ``OpenOrchestra\BaseApi\Exceptions\TransformerParameterTypeException``
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/81
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1631
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/218
>  move TransformerParameterTypeException to base api bundle 1.1

- composer.json
[OO-BUGFIX] maximun version for nodejs is ~4.4.3
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1641
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/223
> Fix nodejs requirement 1.1

- Backoffice/EventSubscriber/ContentSearchSubscriber.php
- Backoffice/Tests/EventSubscriber/ContentSearchSubscriberTest.php
[OO-BUGFIX] Fix use contentId instead id in ContentSearchSubscriber
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/216
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1667
> use contentId instead id

- BackofficeBundle/Resources/public/coffee/widget/LanguageView.coffee
- BackofficeBundle/Resources/views/BackOffice/Underscore/widgetLanguage._tpl.twig
[OO-BUGFIX] On the node edition page, the node is no more reloaded when clicking on the currently selected language tab
> Don't reload the node when clicking on the currently selected language tab

- BackofficeBundle/Resources/public/coffee/widget/LanguageView.coffee
- BackofficeBundle/Resources/views/BackOffice/Underscore/widgetLanguage._tpl.twig
[OO-BUGFIX] On the node edition page, the node is no more reloaded when clicking on the currently selected language tab
> 1 1 fix language tabs

- ApiBundle/Tests/Transformer/NodeGroupRoleTransformerTest.php
- ApiBundle/Transformer/NodeGroupRoleTransformer.php
[OO-BUGFIX] Use the site binded to the group when setting a node role instead of the currently selected site
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1738
https://github.com/open-orchestra/open-orchestra-model-interface/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/591
> Use the site binded to the group when setting a node role instead of the currentSite

- ApiBundle/Tests/Transformer/NodeGroupRoleTransformerTest.php
- ApiBundle/Transformer/NodeGroupRoleTransformer.php
[OO-BUGFIX] Use the site binded to the group when setting a node role instead of the currently selected site
https://github.com/open-orchestra/open-orchestra-model-interface/pull/193
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/592
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1741
> 1 2 fix nodegrouprole other currentsite

- ApiBundle/Facade/SiteFacade.php
- ApiBundle/Transformer/SiteTransformer.php
- Backoffice/Form/Type/SiteType.php
- Backoffice/Manager/NodeManager.php
- Backoffice/Tests/Form/Type/SiteTypeTest.php
- Backoffice/Tests/Manager/NodeManagerTest.php
- BackofficeBundle/Resources/config/form.yml
- BackofficeBundle/Resources/public/less/smartadminPatches/form.less
- BackofficeBundle/Resources/public/less/smartadminPatches/tab.less
[OO-FEATURE] On a site, the default Meta Description and Meta Keywords can now be personnalized per language
https://github.com/open-orchestra/open-orchestra-model-interface/pull/195
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/33
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/595
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1757
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/171
> 1 2 multi languages meta

- Backoffice/EventSubscriber/AbstractModulableTypeSubscriber.php
- Backoffice/EventSubscriber/BlockFormTypeSubscriber.php
- Backoffice/EventSubscriber/BlockTypeSubscriber.php
- Backoffice/Form/Type/BlockType.php
- Backoffice/GenerateForm/Strategies/AbstractBlockStrategy.php
- Backoffice/GenerateForm/Strategies/ContentListStrategy.php
- Backoffice/Tests/EventSubscriber/BlockFormTypeSubscriberTest.php
- Backoffice/Tests/EventSubscriber/BlockTypeSubscriberTest.php
- Backoffice/Tests/Form/Type/BlockTypeTest.php
- BackofficeBundle/Controller/BlockController.php
- BackofficeBundle/Resources/config/form.yml
- BackofficeBundle/Resources/config/subscriber.yml
- BackofficeBundle/StrategyManager/GenerateFormManager.php
- BackofficeBundle/Tests/Functional/EventSubscriber/BlockFormTypeSubscriberTest.php
- BackofficeBundle/Tests/StrategyManager/GenerateFormManagerTest.php
[OO-DEPRECATED] AbstractModulableTypeSubscriber class is deprecated since version 1.2.0 and will be removed in 1.3.0
[OO-DEPRECATED] BlockTypeSubscriber class is deprecated since version 1.2.0 and will be removed in 1.3.0.  use BlockFormTypeSubscriber
[OO-DEPRECATED] GenerateFormManager:createForm method is deprecated since version 1.2.0 and will be removed in 1.3.0.  use getFormType
[OO-BUGFIX] Fix merge form block strategy with transformer and subscriber
> Fix merge form block strategy

- BackofficeBundle/Resources/public/coffee/viewConfigurator.coffee
- GruntTasks/Options/concat.orchestrajs.js
Currently when overriding an OrchestraView object (using the appConfigurationView's configuration) we also need to register a specific route for the case of a refresh of the page. This is due to the fact that the appConfigurationView is not registered before the dom:ready event and that the backbone router is started too early in the process (so my custom configuration is not yet registered when the router tries to match a route).
This change fixes this issue and has no functionnal impact on the application since it's only about JS object creation.
> Create the OrchestraViewConfigurator before dom:ready

- composer.json
[OO-BCBREAK] version of friendsofsymfony/user-bundle is fixed to 2.0.0 alpha3
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1801
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/50
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/141
https://github.com/open-orchestra/open-orchestra/pull/992
> update fos alpha3

- UserAdminBundle/OAuth2/Strategy/ResourceOwnerPasswordGrantStrategy.php
[OO-MISC] The password strategy OAut2 take username and password in the http header.
[OO-BREAK] In the password strategy OAut2 the username and password must be in the request header
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1823
https://github.com/open-orchestra/open-orchestra/pull/1000
https://github.com/open-orchestra/open-orchestra-docs/pull/224
> get password and username and http header for oauth2 password strategy

- Backoffice/Manager/ContentManager.php
- Backoffice/Tests/Manager/ContentManagerTest.php
[OO-BUGFIX] Fix currently published when a published content is duplicate
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1824#issuecomment-234914951
> fix set currently publish to false when duplicate published content 

- ApiBundle/Controller/ContentController.php
[OO-BUGFIX] Fix elements count in content pagination.
[OO-DEPRECATED] ContentRepository::countByContentTypeInLastVersion method is deprecated since version 1.1.3 and will be removed in 2.0, it is replace by ContentRepository::countByContentTypeAndSiteInLastVersion method.
https://github.com/open-orchestra/open-orchestra-model-interface/pull/212
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/621
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1825
> 1.1 fix content pagination count

- BackofficeBundle/Resources/public/coffee/dataTable/DataTableView.coffee
[OO-BUGFIX] No redirect to page 1, when an element of a datable is removed
> fix refresh datable when remove element

- Backoffice/EventSubscriber/ContentTypeSubscriber.php
- Backoffice/Form/Type/ContentType.php
- Backoffice/Tests/EventSubscriber/ContentTypeSubscriberTest.php
- Backoffice/Tests/Form/Type/ContentTypeTest.php
[OO-BUGFIX] Radio button `Link to the current site` is only available when you create a content
> remove radio button linked to site when edit content

- Backoffice/EventSubscriber/ContentTypeSubscriber.php
- Backoffice/Form/Type/ContentType.php
- Backoffice/Tests/EventSubscriber/ContentTypeSubscriberTest.php
- Backoffice/Tests/Form/Type/ContentTypeTest.php
[OO-BUGFIX] Radio button Link to the current site is only available when you create a content
cherry-pick https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1827
> remove radio button linked to site when edit content (#1827)

- ApiBundle/Resources/config/transformer.yml
- ApiBundle/Tests/Transformer/BlockTransformerTest.php
- ApiBundle/Transformer/BlockTransformer.php
[OO-FEATURE] Add a query parameter `cache=private` in the url when a private block is rendering
https://github.com/open-orchestra/open-orchestra-docs/pull/229
https://github.com/open-orchestra/open-orchestra-provision/pull/41
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/636
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1853
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/191
> specify block cache

- Backoffice/Security/Authorization/Voter/DeleteStatusVoter.php
- Backoffice/Tests/Security/Authorization/Voter/DeleteStatusVoterTest.php
[OO-HOTFIX] Temporary disable the possibility to delete a status in order to speed up significantly API responses including status
> DeleteStatusVoter always return false to avoid long facade generation

- Backoffice/Security/Authorization/Voter/DeleteStatusVoter.php
- Backoffice/Tests/Security/Authorization/Voter/DeleteStatusVoterTest.php
[OO-HOTFIX] Temporary disable the possibility to delete a status in order to speed up significantly API responses including status
> 1.1 DeleteStatusVoter always return false to avoid long facade generation

- ApiBundle/Transformer/NodeTransformer.php
[OO-BCBREAK] Remove a useless parameter on open_orchestra_base_node_preview route
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/117
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/202
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1971
> Remive nodeId as a paramter on open_orchestra_base_node_preview

- ApiBundle/Transformer/NodeTransformer.php
[OO-BCBREAK] Remove a useless parameter on open_orchestra_base_node_preview route
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/118
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2002
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/203
> Remive nodeId as a paramter on open_orchestra_base_node_preview (#1971)

- Backoffice/Form/Type/NodeType.php
- BackofficeBundle/Resources/public/less/openorchestra.less
[OO-FEATURE] In node edition, publishing and unpublishing dates can be selected via a date picker
> Change publication date form type from date to oo_date_picker

- Backoffice/Context/ContextManager.php
- Backoffice/Tests/Context/ContextManagerTest.php
- BackofficeBundle/StrategyManager/AuthorizeStatusChangeManager.php
- BackofficeBundle/Tests/StrategyManager/AuthorizeStatusChangeManagerTest.php
- UserAdminBundle/DataFixtures/MongoDB/LoadUserData.php
[OO-BCBREAK] The use of super admin functionality is removed. use now role DEVELOPER and PLATFORM_ADMIN
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2021
https://github.com/open-orchestra/open-orchestra/pull/1104
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/326
> remove super admin

- Backoffice/Form/DataTransformer/ChoicesOptionToArrayTransformer.php
[OO-BUGFIX] Fix ChoicesOptionToArrayTransformer when data is not of the correct type
> Fix ChoicesOptionToArrayTransformer when data is not of the correct type
